"""
Pure-Python Access backend tests.

These tests verify the byte-level parser in ``pyopenvba.access_read`` against a
ground-truth oracle generated by Access COM (``tests/live_access_test/_oracle.ps1``).
The COM oracle is *only* used to produce the expected output; the implementation
under test (`pyopenvba.access_read`) is pure Python with no third-party deps.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from pyopenvba.access_read import (
    ACE_PAGE_SIZE,
    PAGE_TYPE_DB_DEF,
    PAGE_TYPE_LVAL,
    AccessReader,
    SourceRow,
)

FIXTURES = Path(__file__).parent / "live_access_test"
ACCDB = FIXTURES / "New Microsoft Access Database.accdb"
ORACLE_DIR = FIXTURES / "_oracle_out"

requires_live = pytest.mark.skipif(
    not ACCDB.exists(),
    reason="live .accdb fixture not present",
)

# Two standard modules that Access happened to store on the same LVAL
# page: ModA computes 2 * 3, ModB computes 5 + 1.
TWO_MODULES = FIXTURES / "two_modules_one_page.accdb"

requires_two_modules = pytest.mark.skipif(
    not TWO_MODULES.exists(),
    reason="two-module .accdb fixture not present",
)


# One module too large for a 4 KiB page, so Access chained its stream
# across several LVAL rows. BigCalc sums 2*i-1 for i in 1..120 = 14400.
SPANNING = FIXTURES / "module_spanning_pages.accdb"

requires_spanning = pytest.mark.skipif(
    not SPANNING.exists(),
    reason="page-spanning .accdb fixture not present",
)


@requires_spanning
def test_module_spanning_pages_yields_one_module() -> None:
    """A chained module is one module, not one per row it touches."""
    with AccessReader(SPANNING) as db:
        assert [m.name for m in db.iter_vba_modules()] == ["M"]
        assert [s.name for s in db.find_module_streams()] == ["M"]


@requires_spanning
def test_module_spanning_pages_decodes_all_pcode() -> None:
    """The stream is the assembled chain, not just its head row."""
    with AccessReader(SPANNING) as db:
        stream = db.find_module_streams()[0]
        # The head row alone is one page; the real stream is far bigger.
        assert len(stream.raw) > ACE_PAGE_SIZE
        module = db.disassemble_module("M")
        with_pcode = [ln for ln in module.lines if ln.instructions]
        assert len(with_pcode) > 100
        literals = [
            value
            for line in module.lines
            for instruction in line.instructions
            if instruction.mnemonic == "LitDI2"
            for _, value in instruction.operands
        ]
        # The final statement is `tally = tally + 120 * 2 - 1`.
        assert literals[-4:] == [1, 120, 2, 1]


@requires_two_modules
def test_module_streams_are_found_per_module_not_per_page() -> None:
    """Modules sharing an LVAL page each get their own carrier row."""
    with AccessReader(TWO_MODULES) as db:
        names = sorted(m.name for m in db.iter_vba_modules())
        assert names == ["ModA", "ModB"]
        streams = db.find_module_streams()
        assert sorted(s.name for s in streams) == ["ModA", "ModB"]
        # Same page, distinct rows -- the case that page-keyed lookup lost.
        assert len({s.page for s in streams}) == 1
        assert len({s.slot for s in streams}) == 2


@requires_two_modules
def test_disassemble_module_picks_the_named_module() -> None:
    """Each module disassembles to its own p-code, not a page neighbour's."""
    with AccessReader(TWO_MODULES) as db:
        def literals(name: str) -> list[int]:
            return [
                value
                for line in db.disassemble_module(name).lines
                for instruction in line.instructions
                if instruction.mnemonic == "LitDI2"
                for _, value in instruction.operands
            ]

        assert literals("ModA") == [2, 3]
        assert literals("ModB") == [5, 1]


@requires_live
def test_open_and_validate_header() -> None:
    with AccessReader(ACCDB) as db:
        assert db.format == "ace"
        assert db.page_count == ACCDB.stat().st_size // ACE_PAGE_SIZE


@requires_live
def test_page_zero_is_db_def() -> None:
    with AccessReader(ACCDB) as db:
        assert db.page_type(0) == PAGE_TYPE_DB_DEF


@requires_live
def test_read_page_returns_full_page() -> None:
    with AccessReader(ACCDB) as db:
        page = db.read_page(0)
        assert len(page) == ACE_PAGE_SIZE


@requires_live
def test_read_page_bounds() -> None:
    from pyopenvba.access_read import AccessError
    with AccessReader(ACCDB) as db:
        with pytest.raises(AccessError):
            db.read_page(-1)
        with pytest.raises(AccessError):
            db.read_page(db.page_count)


@requires_live
def test_lval_pages_are_findable() -> None:
    """
    The live fixture contains long VBA module source stored across LVAL
    (page type 0x08 or page type 0x01 with the literal 'LVAL' tag at +4)
    pages. Verify at least one such page exists.
    """
    with AccessReader(ACCDB) as db:
        found = 0
        for i in range(db.page_count):
            p = db.read_page(i)
            if p[0] == PAGE_TYPE_LVAL or p[4:8] == b"LVAL":
                found += 1
        assert found > 0, "expected at least one LVAL page in the live fixture"


@requires_live
def test_iter_source_rows_finds_comment_lines() -> None:
    """
    The fixture's two modules each contain 1000 distinctive comment lines.
    The pure-Python row scanner must find them all (2000 total) with the
    exact line text used to author the fixture.
    """
    # Each authored line is "' N    This is a VBA comment line with line number"
    # where the number is left-justified in a 5-char field padded with spaces,
    # preceded by one space, followed by one space, then "This is a VBA ...".
    # On disk the leading apostrophe is stripped (see SourceRow.to_source_line).
    expected_texts = {
        f" {n}{' ' * (5 - len(str(n)))}This is a VBA comment line with line number"
        for n in range(1, 1001)
    }
    with AccessReader(ACCDB) as db:
        rows = list(db.iter_source_rows())
        assert all(isinstance(r, SourceRow) for r in rows)
        # Two identical 1000-line modules -> at least 2000 rows.
        assert len(rows) >= 2000, f"only {len(rows)} rows found"
        decoded = {r.text.decode("ascii") for r in rows}
        # Every expected comment-line payload must appear at least once.
        missing = expected_texts - decoded
        assert not missing, f"missing {len(missing)} expected rows: {sorted(missing)[:3]}"


@requires_live
def test_source_row_round_trip_reconstructs_comment_prefix() -> None:
    """
    Comment rows have the leading apostrophe-space stripped on disk.
    SourceRow.to_source_line() must put them back exactly.
    """
    expected_first = "' 1    This is a VBA comment line with line number"
    with AccessReader(ACCDB) as db:
        for row in db.iter_source_rows():
            if row.text.startswith(b" 1    This"):
                assert row.to_source_line() == expected_first
                return
    pytest.fail("did not find the row for source line 1")


# ---------------------------------------------------------------------------
# VBA module discovery & extraction (MS-OVBA blob decode).
# ---------------------------------------------------------------------------


@requires_live
def test_vba_module_names_match_oracle_manifest() -> None:
    """
    The pure-Python module discovery must report exactly the same set of
    module names as Access COM exposes via VBE.ActiveVBProject.VBComponents.
    """
    import json

    manifest_path = ORACLE_DIR / "manifest.json"
    if not manifest_path.exists():
        pytest.skip("oracle manifest not present; re-run tests/live_access_test/_oracle.ps1")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8-sig"))
    expected = {entry["Name"] for entry in manifest}
    with AccessReader(ACCDB) as db:
        actual = set(db.vba_module_names())
    assert actual == expected, f"oracle has {expected}, pyopenvba has {actual}"


@requires_live
@pytest.mark.parametrize(
    "module_name",
    ["Module1", "Class1", "Module2"],
)
def test_read_vba_module_matches_oracle_byte_for_byte(module_name: str) -> None:
    """
    The decompressed source from pyopenvba.access_read must match Access COM's
    CodeModule.Lines() output byte-for-byte (after CRLF -> LF normalization
    and trailing-newline stripping, which are artifacts of how the oracle
    writes its file vs. how the on-disk stream stores line endings).
    """
    oracle_path = ORACLE_DIR / f"{module_name}.bas.txt"
    if not oracle_path.exists():
        pytest.skip(f"oracle {oracle_path.name} not present")
    oracle = (
        oracle_path.read_text(encoding="utf-8")
        .replace("\r\n", "\n")
        .rstrip("\n")
    )
    with AccessReader(ACCDB) as db:
        py_src = db.read_vba_module(module_name).replace("\r\n", "\n").rstrip("\n")
    assert py_src == oracle, (
        f"{module_name} mismatch: py len={len(py_src)} oracle len={len(oracle)}"
    )


@requires_live
def test_iter_vba_modules_yields_attribute_block() -> None:
    """
    Every discovered VBA module must carry an ``Attribute VB_Name = "..."``
    line in its attributes preamble (this is what we use to identify the
    module). The body must NOT begin with an Attribute line.
    """
    with AccessReader(ACCDB) as db:
        modules = list(db.iter_vba_modules())
    assert modules, "expected at least one VBA module in the fixture"
    for m in modules:
        assert f'Attribute VB_Name = "{m.name}"' in m.attributes_text
        assert not m.source.startswith("Attribute "), (
            f"module {m.name!r} body still has Attribute preamble: "
            f"{m.source[:80]!r}"
        )


@requires_live
def test_read_vba_module_unknown_name_raises() -> None:
    from pyopenvba.access_read import AccessError

    with AccessReader(ACCDB) as db, pytest.raises(AccessError):
        db.read_vba_module("DoesNotExist_zzzzz")



# ---------------------------------------------------------------------------
# Non-ASCII source text and identifiers
#
# Access stores VBA source lines and identifier names MBCS-encoded in the
# project's code page, not as ASCII. Decoding them as ASCII raised
# UnicodeDecodeError on any accented or non-Latin text, and the byte
# filters that guard both scanners rejected every byte above 0x7E, so such
# rows and identifiers were silently dropped before they could be decoded.
# These tests pin the code-page behaviour; they need no fixture database.
# ---------------------------------------------------------------------------

@pytest.mark.parametrize(
    ("code_page", "text"),
    [
        (1252, "Betr\u00e4ge pr\u00fcfen"),      # German, Latin-1
        (1252, "caf\u00e9 na\u00efve"),          # French accents
        (1251, "\u041f\u0440\u0438\u0432\u0435\u0442"),   # Cyrillic
        (1253, "\u0393\u03b5\u03b9\u03b1"),      # Greek
        (1252, "plain ascii comment"),           # unchanged behaviour
    ],
)
def test_source_row_decodes_with_project_code_page(
    code_page: int, text: str
) -> None:
    """A comment row round-trips through its code page, apostrophe restored."""
    from pyopenvba.access_read import SourceRow

    raw = text.encode(f"cp{code_page}")
    row = SourceRow(
        offset=0, row_type="comment", length=len(raw), text=raw,
        code_page=code_page,
    )
    assert row.to_source_line() == "'" + text


def test_source_row_code_page_defaults_to_1252() -> None:
    """Constructing without a code page keeps the pre-existing signature."""
    from pyopenvba.access_read import SourceRow

    row = SourceRow(0, "comment", 5, b"hello")
    assert row.code_page == 1252
    assert row.to_source_line() == "'hello"


def _identifier_record(name: str, code_page: int, type_byte: int = 0x04) -> bytes:
    body = name.encode(f"cp{code_page}")
    return bytes((len(body), type_byte)) + body + b"\x00\x00\x10\x00"


@pytest.mark.parametrize(
    ("code_page", "names"),
    [
        (1252, ["Modul", "Betr\u00e4ge", "Wert"]),
        (1251, ["Modul", "\u041c\u043e\u0434\u0443\u043b\u044c"]),
    ],
)
def test_identifier_table_keeps_non_ascii_names(
    code_page: int, names: list[str]
) -> None:
    """Identifiers outside ASCII survive the scan and decode correctly."""
    from pyopenvba import access_read as _access

    parse = getattr(_access, "_parse_vba_project_identifiers")

    stream = b"\x02\x00\x06\x04Access"
    for name in names:
        stream += _identifier_record(name, code_page)
    stream += b"\x02\xff\xff\x01\x01"

    parsed = parse(stream, code_page)
    assert [i.name for i in parsed] == ["Access", *names]


def _slotted_identifier_record(name: str, slot: int) -> bytes:
    """An identifier record that carries its own operand slot.

    Access emits this form for a few names that bind to a pre-existing
    low-numbered slot instead of being appended positionally. Layout,
    measured from Access-built databases::

        00 00 <u16 slot> <u8 len> 80 10 00 ff 03 00 00 <name>

    It has no trailing id/``10 00`` pair, which is what makes the
    canonical record walker reject it.
    """
    body = name.encode("cp1252")
    return (b"\x00\x00" + slot.to_bytes(2, "little") + bytes((len(body), 0x80))
            + b"\x10\x00\xff\x03\x00\x00" + body)


def test_identifier_table_parses_explicitly_slotted_record() -> None:
    """A slotted record is surfaced, not swallowed into the next prefix."""
    from pyopenvba import access_read as _access

    parse = getattr(_access, "_parse_vba_project_identifiers")

    stream = (b"\x02\x00\x06\x04Access"
              + _slotted_identifier_record("b", 11)
              + _identifier_record("VBA", 1252)
              + b"\x02\xff\xff\x01\x01")

    parsed = parse(stream, 1252)
    assert [i.name for i in parsed] == ["Access", "b", "VBA"]
    slotted = next(i for i in parsed if i.name == "b")
    assert slotted.slot == 11
    # It must not be absorbed as opaque bytes on the following record.
    assert next(i for i in parsed if i.name == "VBA").prefix == b""


def test_slotted_identifier_does_not_shift_positional_indices() -> None:
    """Positional indices skip slotted records.

    p-code addresses positional identifiers as ``524 + 2*index``, so
    counting a slotted record would misname every identifier after it.
    A slotted record carries its own operand (``2*slot + 2``) instead.
    """
    from pyopenvba import access_read as _access

    parse = getattr(_access, "_parse_vba_project_identifiers")

    stream = (b"\x02\x00\x06\x04Access"
              + _slotted_identifier_record("b", 11)
              + _identifier_record("VBA", 1252)
              + _identifier_record("zz", 1252)
              + b"\x02\xff\xff\x01\x01")

    parsed = parse(stream, 1252)
    positional = {i.name: i.index for i in parsed if i.slot is None}
    assert positional == {"Access": 0, "VBA": 1, "zz": 2}
    assert next(i for i in parsed if i.name == "b").index == -1
