"""
Pure-Python Access backend tests.

These tests verify the byte-level parser in ``pyopenvba.access_read`` against a
ground-truth oracle generated by Access COM (``tests/live_access_test/_oracle.ps1``).
The COM oracle is *only* used to produce the expected output; the implementation
under test (`pyopenvba.access_read`) is pure Python with no third-party deps.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from pyopenvba.access_read import (
    ACE_PAGE_SIZE,
    PAGE_TYPE_DB_DEF,
    PAGE_TYPE_LVAL,
    AccessReader,
    SourceRow,
)

FIXTURES = Path(__file__).parent / "live_access_test"
ACCDB = FIXTURES / "New Microsoft Access Database.accdb"
ORACLE_DIR = FIXTURES / "_oracle_out"

requires_live = pytest.mark.skipif(
    not ACCDB.exists(),
    reason="live .accdb fixture not present",
)


@requires_live
def test_open_and_validate_header() -> None:
    with AccessReader(ACCDB) as db:
        assert db.format == "ace"
        assert db.page_count == ACCDB.stat().st_size // ACE_PAGE_SIZE


@requires_live
def test_page_zero_is_db_def() -> None:
    with AccessReader(ACCDB) as db:
        assert db.page_type(0) == PAGE_TYPE_DB_DEF


@requires_live
def test_read_page_returns_full_page() -> None:
    with AccessReader(ACCDB) as db:
        page = db.read_page(0)
        assert len(page) == ACE_PAGE_SIZE


@requires_live
def test_read_page_bounds() -> None:
    from pyopenvba.access_read import AccessError
    with AccessReader(ACCDB) as db:
        with pytest.raises(AccessError):
            db.read_page(-1)
        with pytest.raises(AccessError):
            db.read_page(db.page_count)


@requires_live
def test_lval_pages_are_findable() -> None:
    """
    The live fixture contains long VBA module source stored across LVAL
    (page type 0x08 or page type 0x01 with the literal 'LVAL' tag at +4)
    pages. Verify at least one such page exists.
    """
    with AccessReader(ACCDB) as db:
        found = 0
        for i in range(db.page_count):
            p = db.read_page(i)
            if p[0] == PAGE_TYPE_LVAL or p[4:8] == b"LVAL":
                found += 1
        assert found > 0, "expected at least one LVAL page in the live fixture"


@requires_live
def test_iter_source_rows_finds_comment_lines() -> None:
    """
    The fixture's two modules each contain 1000 distinctive comment lines.
    The pure-Python row scanner must find them all (2000 total) with the
    exact line text used to author the fixture.
    """
    # Each authored line is "' N    This is a VBA comment line with line number"
    # where the number is left-justified in a 5-char field padded with spaces,
    # preceded by one space, followed by one space, then "This is a VBA ...".
    # On disk the leading apostrophe is stripped (see SourceRow.to_source_line).
    expected_texts = {
        f" {n}{' ' * (5 - len(str(n)))}This is a VBA comment line with line number"
        for n in range(1, 1001)
    }
    with AccessReader(ACCDB) as db:
        rows = list(db.iter_source_rows())
        assert all(isinstance(r, SourceRow) for r in rows)
        # Two identical 1000-line modules -> at least 2000 rows.
        assert len(rows) >= 2000, f"only {len(rows)} rows found"
        decoded = {r.text.decode("ascii") for r in rows}
        # Every expected comment-line payload must appear at least once.
        missing = expected_texts - decoded
        assert not missing, f"missing {len(missing)} expected rows: {sorted(missing)[:3]}"


@requires_live
def test_source_row_round_trip_reconstructs_comment_prefix() -> None:
    """
    Comment rows have the leading apostrophe-space stripped on disk.
    SourceRow.to_source_line() must put them back exactly.
    """
    expected_first = "' 1    This is a VBA comment line with line number"
    with AccessReader(ACCDB) as db:
        for row in db.iter_source_rows():
            if row.text.startswith(b" 1    This"):
                assert row.to_source_line() == expected_first
                return
    pytest.fail("did not find the row for source line 1")


# ---------------------------------------------------------------------------
# VBA module discovery & extraction (MS-OVBA blob decode).
# ---------------------------------------------------------------------------


@requires_live
def test_vba_module_names_match_oracle_manifest() -> None:
    """
    The pure-Python module discovery must report exactly the same set of
    module names as Access COM exposes via VBE.ActiveVBProject.VBComponents.
    """
    import json

    manifest_path = ORACLE_DIR / "manifest.json"
    if not manifest_path.exists():
        pytest.skip("oracle manifest not present; re-run tests/live_access_test/_oracle.ps1")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8-sig"))
    expected = {entry["Name"] for entry in manifest}
    with AccessReader(ACCDB) as db:
        actual = set(db.vba_module_names())
    assert actual == expected, f"oracle has {expected}, pyopenvba has {actual}"


@requires_live
@pytest.mark.parametrize(
    "module_name",
    ["Module1", "Class1", "Module2"],
)
def test_read_vba_module_matches_oracle_byte_for_byte(module_name: str) -> None:
    """
    The decompressed source from pyopenvba.access_read must match Access COM's
    CodeModule.Lines() output byte-for-byte (after CRLF -> LF normalization
    and trailing-newline stripping, which are artifacts of how the oracle
    writes its file vs. how the on-disk stream stores line endings).
    """
    oracle_path = ORACLE_DIR / f"{module_name}.bas.txt"
    if not oracle_path.exists():
        pytest.skip(f"oracle {oracle_path.name} not present")
    oracle = (
        oracle_path.read_text(encoding="utf-8")
        .replace("\r\n", "\n")
        .rstrip("\n")
    )
    with AccessReader(ACCDB) as db:
        py_src = db.read_vba_module(module_name).replace("\r\n", "\n").rstrip("\n")
    assert py_src == oracle, (
        f"{module_name} mismatch: py len={len(py_src)} oracle len={len(oracle)}"
    )


@requires_live
def test_iter_vba_modules_yields_attribute_block() -> None:
    """
    Every discovered VBA module must carry an ``Attribute VB_Name = "..."``
    line in its attributes preamble (this is what we use to identify the
    module). The body must NOT begin with an Attribute line.
    """
    with AccessReader(ACCDB) as db:
        modules = list(db.iter_vba_modules())
    assert modules, "expected at least one VBA module in the fixture"
    for m in modules:
        assert f'Attribute VB_Name = "{m.name}"' in m.attributes_text
        assert not m.source.startswith("Attribute "), (
            f"module {m.name!r} body still has Attribute preamble: "
            f"{m.source[:80]!r}"
        )


@requires_live
def test_read_vba_module_unknown_name_raises() -> None:
    from pyopenvba.access_read import AccessError

    with AccessReader(ACCDB) as db, pytest.raises(AccessError):
        db.read_vba_module("DoesNotExist_zzzzz")


