"""
Pure-Python Access backend tests.

These tests verify the byte-level parser in ``pyopenvba.access`` against a
ground-truth oracle generated by Access COM (``tests/live_access_test/_oracle.ps1``).
The COM oracle is *only* used to produce the expected output; the implementation
under test (`pyopenvba.access`) is pure Python with no third-party deps.
"""

from __future__ import annotations

import pytest
from pathlib import Path

from pyopenvba.access import (
    ACE_PAGE_SIZE,
    AccessFile,
    PAGE_TYPE_DB_DEF,
    PAGE_TYPE_LVAL,
    SourceRow,
)


FIXTURES = Path(__file__).parent / "live_access_test"
ACCDB = FIXTURES / "New Microsoft Access Database.accdb"
ORACLE_DIR = FIXTURES / "_oracle_out"

requires_live = pytest.mark.skipif(
    not ACCDB.exists(),
    reason="live .accdb fixture not present",
)


@requires_live
def test_open_and_validate_header() -> None:
    with AccessFile(ACCDB) as db:
        assert db.format == "ace"
        assert db.page_count == ACCDB.stat().st_size // ACE_PAGE_SIZE


@requires_live
def test_page_zero_is_db_def() -> None:
    with AccessFile(ACCDB) as db:
        assert db.page_type(0) == PAGE_TYPE_DB_DEF


@requires_live
def test_read_page_returns_full_page() -> None:
    with AccessFile(ACCDB) as db:
        page = db.read_page(0)
        assert len(page) == ACE_PAGE_SIZE


@requires_live
def test_read_page_bounds() -> None:
    with AccessFile(ACCDB) as db:
        with pytest.raises(Exception):
            db.read_page(-1)
        with pytest.raises(Exception):
            db.read_page(db.page_count)


@requires_live
def test_lval_pages_are_findable() -> None:
    """
    The live fixture contains long VBA module source stored across LVAL
    (page type 0x08 or page type 0x01 with the literal 'LVAL' tag at +4)
    pages. Verify at least one such page exists.
    """
    with AccessFile(ACCDB) as db:
        found = 0
        for i in range(db.page_count):
            p = db.read_page(i)
            if p[0] == PAGE_TYPE_LVAL or p[4:8] == b"LVAL":
                found += 1
        assert found > 0, "expected at least one LVAL page in the live fixture"


@requires_live
def test_iter_source_rows_finds_comment_lines() -> None:
    """
    The fixture's two modules each contain 1000 distinctive comment lines.
    The pure-Python row scanner must find them all (2000 total) with the
    exact line text used to author the fixture.
    """
    # Each authored line is "' N    This is a VBA comment line with line number"
    # where the number is left-justified in a 5-char field padded with spaces,
    # preceded by one space, followed by one space, then "This is a VBA ...".
    # On disk the leading apostrophe is stripped (see SourceRow.to_source_line).
    expected_texts = {
        f" {n}{' ' * (5 - len(str(n)))}This is a VBA comment line with line number"
        for n in range(1, 1001)
    }
    with AccessFile(ACCDB) as db:
        rows = list(db.iter_source_rows())
        assert all(isinstance(r, SourceRow) for r in rows)
        # Two identical 1000-line modules -> at least 2000 rows.
        assert len(rows) >= 2000, f"only {len(rows)} rows found"
        decoded = {r.text.decode("ascii") for r in rows}
        # Every expected comment-line payload must appear at least once.
        missing = expected_texts - decoded
        assert not missing, f"missing {len(missing)} expected rows: {sorted(missing)[:3]}"


@requires_live
def test_source_row_round_trip_reconstructs_comment_prefix() -> None:
    """
    Comment rows have the leading apostrophe-space stripped on disk.
    SourceRow.to_source_line() must put them back exactly.
    """
    expected_first = "' 1    This is a VBA comment line with line number"
    with AccessFile(ACCDB) as db:
        for row in db.iter_source_rows():
            if row.text.startswith(b" 1    This"):
                assert row.to_source_line() == expected_first
                return
    pytest.fail("did not find the row for source line 1")


# ---------------------------------------------------------------------------
# VBA module discovery & extraction (MS-OVBA blob decode).
# ---------------------------------------------------------------------------


@requires_live
def test_vba_module_names_match_oracle_manifest() -> None:
    """
    The pure-Python module discovery must report exactly the same set of
    module names as Access COM exposes via VBE.ActiveVBProject.VBComponents.
    """
    import json

    manifest_path = ORACLE_DIR / "manifest.json"
    if not manifest_path.exists():
        pytest.skip("oracle manifest not present; re-run tests/live_access_test/_oracle.ps1")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8-sig"))
    expected = {entry["Name"] for entry in manifest}
    with AccessFile(ACCDB) as db:
        actual = set(db.vba_module_names())
    assert actual == expected, f"oracle has {expected}, pyopenvba has {actual}"


@requires_live
@pytest.mark.parametrize(
    "module_name",
    ["Module1", "Class1", "Module2"],
)
def test_read_vba_module_matches_oracle_byte_for_byte(module_name: str) -> None:
    """
    The decompressed source from pyopenvba.access must match Access COM's
    CodeModule.Lines() output byte-for-byte (after CRLF -> LF normalization
    and trailing-newline stripping, which are artifacts of how the oracle
    writes its file vs. how the on-disk stream stores line endings).
    """
    oracle_path = ORACLE_DIR / f"{module_name}.bas.txt"
    if not oracle_path.exists():
        pytest.skip(f"oracle {oracle_path.name} not present")
    oracle = (
        oracle_path.read_text(encoding="utf-8")
        .replace("\r\n", "\n")
        .rstrip("\n")
    )
    with AccessFile(ACCDB) as db:
        py_src = db.read_vba_module(module_name).replace("\r\n", "\n").rstrip("\n")
    assert py_src == oracle, (
        f"{module_name} mismatch: py len={len(py_src)} oracle len={len(oracle)}"
    )


@requires_live
def test_iter_vba_modules_yields_attribute_block() -> None:
    """
    Every discovered VBA module must carry an ``Attribute VB_Name = "..."``
    line in its attributes preamble (this is what we use to identify the
    module). The body must NOT begin with an Attribute line.
    """
    with AccessFile(ACCDB) as db:
        modules = list(db.iter_vba_modules())
    assert modules, "expected at least one VBA module in the fixture"
    for m in modules:
        assert f'Attribute VB_Name = "{m.name}"' in m.attributes_text
        assert not m.source.startswith("Attribute "), (
            f"module {m.name!r} body still has Attribute preamble: "
            f"{m.source[:80]!r}"
        )


@requires_live
def test_read_vba_module_unknown_name_raises() -> None:
    from pyopenvba.access import AccessError

    with AccessFile(ACCDB) as db:
        with pytest.raises(AccessError):
            db.read_vba_module("DoesNotExist_zzzzz")


# ---------------------------------------------------------------------------
# Write path: same-length text patching of the plaintext source store.
#
# Access's authoritative storage for comment bodies and string literals is
# the row-based plaintext store (B9 / E3 markers), NOT the MS-OVBA blob.
# This was verified end-to-end against Access COM and the live VBA editor
# (see docs/architecture.md). The supported write surface is therefore
# same-length byte substitution within those rows.
# ---------------------------------------------------------------------------


@requires_live
def test_replace_text_round_trips_through_disk(tmp_path: Path) -> None:
    """
    Patch a known string literal in Module2 ("This is a test 1" -> a
    same-length replacement), save to a temp copy, reopen, and verify
    both that the bytes round-tripped and that the original buffer is
    not visible in the patched region anymore.
    """
    out = tmp_path / "patched.accdb"
    with AccessFile(ACCDB) as db:
        n = db.replace_text("This is a test 1", "Hello from py!!!")
        assert n >= 1
        db.save(out)
        # The in-memory path should have been updated to the new location.
        assert db.path == out

    # Reopen the saved file and confirm the patch survived to disk.
    raw = out.read_bytes()
    assert b"Hello from py!!!" in raw
    # Count of new strings must be >= replacements we just made.
    assert raw.count(b"Hello from py!!!") >= n


@requires_live
def test_replace_text_rejects_length_mismatch() -> None:
    from pyopenvba.access import AccessError

    with AccessFile(ACCDB) as db:
        with pytest.raises(AccessError, match="same-length"):
            db.replace_text("This is a test 1", "short")


@requires_live
def test_replace_text_rejects_missing_pattern() -> None:
    from pyopenvba.access import AccessError

    with AccessFile(ACCDB) as db:
        with pytest.raises(AccessError, match="not found"):
            db.replace_text("ZZZ_no_such_text_in_file_ZZZ", "AAA_no_such_text_in_file_AAA")


@requires_live
def test_replace_text_rejects_empty_old() -> None:
    from pyopenvba.access import AccessError

    with AccessFile(ACCDB) as db:
        with pytest.raises(AccessError, match="non-empty"):
            db.replace_text("", "")


@requires_live
def test_replace_text_count_caps_replacements() -> None:
    """
    The comment-line block contains 1000+ rows that share the substring
    "This is a VBA comment line". With ``count=1`` only one row is patched.
    """
    with AccessFile(ACCDB) as db:
        n = db.replace_text(
            "This is a VBA comment line",
            "This was the vba COMMENT!.",  # exact same length (26 chars)
            count=1,
        )
        assert n == 1


@requires_live
def test_replace_text_accepts_bytes_operands(tmp_path: Path) -> None:
    """Bytes operands should be accepted as-is without encoding."""
    out = tmp_path / "bytes_patched.accdb"
    with AccessFile(ACCDB) as db:
        n = db.replace_text(b"This is a test 2", b"Hello bytes mode")
        assert n >= 1
        db.save(out)
    assert b"Hello bytes mode" in out.read_bytes()


@requires_live
def test_save_without_path_overwrites_in_place(tmp_path: Path) -> None:
    """
    save(path=None) must write back to whatever path the file was opened
    from. To avoid mutating the canonical fixture, we first stage a copy.
    """
    staged = tmp_path / "stage.accdb"
    staged.write_bytes(ACCDB.read_bytes())

    with AccessFile(staged) as db:
        db.replace_text("This is a test 3", "InPlaceSave_PATCH"[:16])
        db.save()  # no path -> overwrite staged in place

    assert b"InPlaceSave_PATC" in staged.read_bytes()


# ---------------------------------------------------------------------------
# RE corpus regression: the reader must work on small databases that lay out
# the VBA project across multiple separate LVAL rows rather than one big
# chained long-value. See docs/access_pcode_re.md Phase 2.
# ---------------------------------------------------------------------------

_RE_CORPUS = FIXTURES / "re_corpus" / "samples"


@pytest.mark.skipif(
    not (_RE_CORPUS / "040__sub_msgbox_hello.accdb").exists(),
    reason="RE corpus not generated; run tests/live_access_test/_corpus_generate.ps1",
)
def test_corpus_small_sample_module_discovery() -> None:
    db = AccessFile(_RE_CORPUS / "040__sub_msgbox_hello.accdb")
    assert db.vba_module_names() == ["M"]
    src = db.read_vba_module("M")
    assert 'MsgBox "hello"' in src
    assert "Sub A()" in src
    assert "End Sub" in src


@pytest.mark.skipif(
    not _RE_CORPUS.exists(),
    reason="RE corpus not generated",
)
def test_corpus_module_names_match_filename_hints() -> None:
    """Every sample whose filename encodes a module name must expose that
    exact module name through the pure-Python reader."""
    cases = {
        "010__empty_StdModule_M.accdb": ["M"],
        "011__empty_StdModule_AB.accdb": ["AB"],
        "012__empty_StdModule_ABC.accdb": ["ABC"],
        "013__empty_StdModule_Mod1.accdb": ["Mod1"],
        "014__empty_StdModule_Module1.accdb": ["Module1"],
        "015__empty_StdModule_LongName.accdb": ["ThisIsALongModuleName"],
        "020__empty_ClassModule_C.accdb": ["C"],
        "021__empty_ClassModule_Class1.accdb": ["Class1"],
    }
    for filename, expected in cases.items():
        path = _RE_CORPUS / filename
        if not path.exists():
            continue
        db = AccessFile(path)
        assert db.vba_module_names() == expected, f"{filename}: {db.vba_module_names()}"


