"""How tall a font makes a row, as Excel measures it on a 96-DPI display.

Generated by scripts/bake_font_rows.py from tests/fixtures/font_rows.json,
which scripts/measure_font_heights.py measured in live Excel. For each font
and style, at every pixel size from 1 to 546 (409.5pt), the table holds
the height in pixels of a row whose only font besides the Normal one it
is, and the descent Excel writes for that row, in twips. The heights follow
each font's hinted metrics irregularly enough that no formula over the
font's own tables reproduces them. Do not edit by hand.
"""

from __future__ import annotations

from functools import cache

MOST_PIXELS = 546
#: One letter per step from one pixel size to the next; "a" is -2.
_ALPHABET = "abcdefghijklmnopqrstuvwxyz"
_LOWEST = -2
#: Each table: the first row height and descent, then the steps of each.
_TABLES: tuple[tuple[int, int, str, str], ...] = (
    (20, 5,
     "ccccccccccccccdedddeddedddeddedddedddeddedddedddedfedddedddeddedddeddedddedddeddedddedddeddedddeddde"
     "ddedddeddedddedddeddedddedddeddedddedddeddedddeddeddfedddeddedddedddeddedddedddeddedddeddedddedddedd"
     "edddedddeddedddedddeddedddeddedddedddeddedddedddeddeddfedddeddedddedddeddedddeddedddedddeddedddeddde"
     "ddedddedddeddedddeddedddedddeddedddedddeddedddedddeddedddgddedddedddeddedddedddeddedddedddeddedddedd"
     "edddedddeddedddedddeddedddedddeddedddeddedddedddeddedddedddgddedddedddeddedddeddedddedddeddedddeddde"
     "ddedddedddeddedddedddeddedddeddedddedddeddedd",
     "cccccccccccccccdcccdccdcccdccdcccdcccdccdcccdcccdcddcccdcccdccdcccdccdcccdcccdccdcccdcccdccdcccdcccd"
     "ccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccdccdccddcccdccdcccdcccdccdcccdcccdccdcccdccdcccdcccdcc"
     "dcccdcccdccdcccdcccdccdcccdccdcccdcccdccdcccdcccdccdccddcccdccdcccdcccdccdcccdccdcccdcccdccdcccdcccd"
     "ccdcccdcccdccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdccceccdcccdcccdccdcccdcccdccdcccdcccdccdcccdcc"
     "dcccdcccdccdcccdcccdccdcccdcccdccdcccdccdcccdcccdccdcccdccceccdcccdcccdccdcccdccdcccdcccdccdcccdcccd"
     "ccdcccdcccdccdcccdcccdccdcccdccdcccdcccdccdcc"),
    (20, 5,
     "ccccccccccccccdddddeddecedddeddddeddeddddedddddeddedddeddddddedddeddeddddddgdddeddedddedcedddeddeddd"
     "eddecddeddedddeddeddddddedddeddedddefcedddeddedddcededdddddedddeeddddddddddeddeeddddddeddddddededfed"
     "ddddddddeeddedddddddededdddddeddedddeddddddeddeddddedcddedfdeddddeddddeddddedddeddddeddddedddedddded"
     "dddeddddedddeddddedfddedddeddddeddddeddddedddeddddeddddedddeddddeddddeddddedddeddfdeddddeddddedddedd"
     "ddeddddedddeddddeddddeddddedddeddddeddddedfdeddddeddddeddddedddeddddeddddedddeddddeddddeddddedddeddd"
     "dedfddedddeddddeddddeddddedddeddddeddddedddde",
     "cccccccccccccccccccdccdbdcccdccccdccdccccdcccccdccdcccdccccccdcccdccdccccccecccdccdcccdcbdcccdccdccc"
     "dccdbccdccdcccdccdccccccdcccdccdcccddbdcccdccdcccbdcdccccccdcccddccccccccccdccddccccccdccccccdcdcddc"
     "ccccccccddccdcccccccdcdccccccdccdcccdccccccdccdccccdcbccdcdcdccccdccccdccccdcccdccccdccccdcccdccccdc"
     "cccdccccdcccdccccdcdccdcccdccccdccccdccccdcccdccccdccccdcccdccccdccccdccccdcccdccdcdccccdccccdcccdcc"
     "ccdccccdcccdccccdccccdccccdcccdccccdccccdcdcdccccdccccdccccdcccdccccdccccdcccdccccdccccdccccdcccdccc"
     "cdcdccdcccdccccdccccdccccdcccdccccdccccdccccd"),
    (20, 5,
     "ccccccccccccccddddedddeddeddddddeeddddddeeddddddeddeddddedddeddeddddddeedddfdddfcdddddedddedddeddddd"
     "ededdddddeddeddddeddddeddedddddededdfdddedddeddedcdddddfddddcdeddeecddedddddededddddeddedddddedddfed"
     "dedddddededdddddeddeddddedddddededdddddededddddeddddecddedfdeddddeddddeddddedddeddddeddddedddedddded"
     "dddeddddedddeddddedfddedddeddddeddddeddddedddeddddeddddedddeddddeddddeddddedddeddfdeddddeddddedddedd"
     "ddeddddedddeddddeddddeddddedddeddddeddddedfdeddddeddddeddddedddeddddeddddedddeddddeddddeddddedddeddd"
     "dedfddedddeddddeddddeddddedddeddddeddddedddde",
     "ccccccccccccccccccdcccdccdccccccddccccccddccccccdccdccccdcccdccdccccccddcccdcccebcccccdcccdcccdccccc"
     "dcdccccccdccdccccdccccdccdcccccdcdccdcccdcccdccdcbccccceccccbcdccddbccdcccccdcdcccccdccdcccccdcccddc"
     "cdcccccdcdccccccdccdccccdcccccdcdccccccdcdcccccdccccdbccdcdcdccccdccccdccccdcccdccccdccccdcccdccccdc"
     "cccdccccdcccdccccdcdccdcccdccccdccccdccccdcccdccccdccccdcccdccccdccccdccccdcccdccdcdccccdccccdcccdcc"
     "ccdccccdcccdccccdccccdccccdcccdccccdccccdcdcdccccdccccdccccdcccdccccdccccdcccdccccdccccdccccdcccdccc"
     "cdcdccdcccdccccdccccdccccdcccdccccdccccdccccd"),
    (20, 5,
     "ccccccccccccccddedddeddddddeddeddddedddedddeddddddfddddddeddddedecddeddedddfdddededdeddddddddfdddedd"
     "ddddddddededddddddeddddededddddeddddgdddedddeddddeddddddeddeddeddddddeddddddfdddddeddddddedddeeddfdd"
     "ddeddddeddeddddeddddeddddddeedddeddddddddeddeeddddddddddedfdeddddeddddeddddedddeddddeddddedddedddded"
     "dddeddddedddeddddedfddedddeddddeddddeddddedddeddddeddddedddeddddeddddeddddedddeddfdeddddeddddedddedd"
     "ddeddddedddeddddeddddeddddedddeddddeddddedfdeddddeddddeddddedddeddddeddddedddeddddeddddeddddedddeddd"
     "dedfddedddeddddeddddeddddedddeddddeddddedddde",
     "ccccccccccccccccdcccdccccccdccdccccdcccdcccdcccccceccccccdccccdcdbccdccdcccdcccdcdccdccccccccecccdcc"
     "ccccccccdcdcccccccdccccdcdcccccdccccecccdcccdccccdccccccdccdccdccccccdccccccecccccdccccccdcccddccdcc"
     "ccdccccdccdccccdccccdccccccddcccdccccccccdccddccccccccccdcdcdccccdccccdccccdcccdccccdccccdcccdccccdc"
     "cccdccccdcccdccccdcdccdcccdccccdccccdccccdcccdccccdccccdcccdccccdccccdccccdcccdccdcdccccdccccdcccdcc"
     "ccdccccdcccdccccdccccdccccdcccdccccdccccdcdcdccccdccccdccccdcccdccccdccccdcccdccccdccccdccccdcccdccc"
     "cdcdccdcccdccccdccccdccccdcccdccccdccccdccccd"),
    (20, 5,
     "ccccccccccccccdddeddddeceddeddddedddedddeddddddededdddedddddededddddedddeddfdeddddeddeddddddededdddd"
     "eddecededdddddeddeddddedddddededdddefddedddddedddcededdddddeceddddfcdddedddeddddedddedddddedddeddgdd"
     "ddddeddeddddeddddeddeddddddededddddeddddededddddddedecddedfdeddddeddddeddddedddeddddeddddedddedddded"
     "dddeddddedddeddddedfddedddeddddeddddeddddedddeddddeddddedddeddddeddddeddddedddeddfdeddddeddddedddedd"
     "ddeddddedddeddddeddddeddddedddeddddeddddedfdeddddeddddeddddedddeddddeddddedddeddddeddddeddddedddeddd"
     "dedfddedddeddddeddddeddddedddeddddeddddedddde",
     "cccccccccccccccccdccccdbdccdccccdcccdcccdccccccdcdccccdcccccdcdcccccdcccdccdcdccccdccdccccccdcdccccc"
     "dccdbdcdccccccdccdccccdcccccdcdccccddccdcccccdcccbdcdccccccdbdccccebcccdcccdccccdcccdcccccdcccdccecc"
     "ccccdccdccccdccccdccdccccccdcdcccccdccccdcdcccccccdcdbccdcdcdccccdccccdccccdcccdccccdccccdcccdccccdc"
     "cccdccccdcccdccccdcdccdcccdccccdccccdccccdcccdccccdccccdcccdccccdccccdccccdcccdccdcdccccdccccdcccdcc"
     "ccdccccdcccdccccdccccdccccdcccdccccdccccdcdcdccccdccccdccccdcccdccccdccccdcccdccccdccccdccccdcccdccc"
     "cdcdccdcccdccccdccccdccccdcccdccccdccccdccccd"),
    (20, 5,
     "ccccccccccccccdedddedddeddedddedddedddeddedddedddeddedddedddedddeddedddedddedddeddedddedddeddedddedd"
     "dedddeddedddedddedddeddedddedddeddedddedddedddeddedddedddeddedddedddedddeddedddedddedddeddedddeddded"
     "dedddedddedddeddedddedddedddeddedddedddeddedddedddedddeddedddedddeddedddedddedddeddedddedddedddedded"
     "ddedddeddedddedddedddeddedddedddeddedddedddedddeddedddedddedddeddedddedddeddedddedddedddeddedddeddde"
     "dddeddedddedddeddedddedddedddeddedddedddeddedddedddedddeddedddedddedddeddedddedddeddedddedddedddedde"
     "dddedddeddedddedddedddeddedddedddedddeddeddde",
     "cccccccccccccccdcccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcc"
     "cdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccdcccdcccdcccdccdcccdcccdc"
     "cdcccdcccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccdcccdcccdcccdccdc"
     "ccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccdcccdcccd"
     "cccdccdcccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccd"
     "cccdcccdccdcccdcccdcccdccdcccdcccdcccdccdcccd"),
    (20, 5,
     "ccccccccccccccdddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddedddd"
     "edddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddedddde"
     "dddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddedddded"
     "ddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedd"
     "deddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddeddd"
     "eddddedddeddddedddeddddedddeddddedddeddddeddd",
     "cccccccccccccccccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdcccc"
     "dcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccd"
     "cccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdc"
     "ccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcc"
     "cdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdccc"
     "dccccdcccdccccdcccdccccdcccdccccdcccdccccdccc"),
    (20, 5,
     "ccccccccccccccddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddeddd"
     "edddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddeddd"
     "edddedddedddedddedddedddedddedddedddedddedddedddedddeddedddedddedddedddedddedddedddedddedddedddeddde"
     "dddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddeddde"
     "dddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddeddde"
     "dddedddeddedddedddedddedddedddedddedddedddedd",
     "ccccccccccccccccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdccc"
     "dcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdccc"
     "dcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccd"
     "cccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccd"
     "cccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccd"
     "cccdcccdccdcccdcccdcccdcccdcccdcccdcccdcccdcc"),
    (20, 5,
     "ccccccccccccccdedddeddedddedddeddedddeddedddedddeddedddedddeddedddedddeddedddedddeddedddedddeddeddde"
     "dddeddedddeddedddedddeddedddedddeddedddedddeddedddedddeddedddedddeddedddedddeddedddeddedddedddeddedd"
     "dedddeddedddedddeddedddedddeddedddedddeddedddedddeddekdddeddeddedddeddeddedddeddeddedddeddeddedddedd"
     "eddedddeddeddedddeddeddedddeddeddedddeddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddeddd"
     "eddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddeddd"
     "eddeddedddeddeddedddeddeddedddeddeddedddedded",
     "cccccccccccccccdcccdccdcccdcccdccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccd"
     "cccdccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccdccdcccdcccdccdcc"
     "cdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdjcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdcc"
     "dccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccc"
     "dccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccc"
     "dccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdc"),
    (20, 5,
     "cccccccccccccddddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddedd"
     "eddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddedd"
     "eddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddedd"
     "eddedddeddeddedddeddeddedddeddeddedddeddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddeddd"
     "eddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddeddd"
     "eddeddedddeddeddedddeddeddedddeddeddedddedded",
     "cccccccccccccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdcc"
     "dccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdcc"
     "dccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdcc"
     "dccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccc"
     "dccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccc"
     "dccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdc"),
    (20, 5,
     "cccccccccccccdddddedddedddeddddedddeeddeddddedddedddedddeddddfdddedddeddddedddedddedddfddddedddeddde"
     "ddddedddeddeeddddedddedddedddeddddedededddeddddedddedddedddededdedddedddeddddedddedddeedddedddeddded"
     "ddeddddedddfdddeddddedddedddedddedddeedddedddeddddeddldddeddeddedddeddeddedddeddeddedddeddeddedddedd"
     "eddedddeddeddedddeddeddedddeddeddedddeddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddeddd"
     "eddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddeddd"
     "eddeddedddeddeddedddeddeddedddeddeddedddedded",
     "cccccccccccccdccccdcccdcccdccccdcccddccdccccdcccdcccdcccdccccecccdcccdccccdcccdcccdccceccccdcccdcccd"
     "ccccdcccdccddccccdcccdcccdcccdccccdcdcdcccdccccdcccdcccdcccdcdccdcccdcccdccccdcccdcccddcccdcccdcccdc"
     "ccdccccdcccecccdccccdcccdcccdcccdcccddcccdcccdccccdcckcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdcc"
     "dccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccc"
     "dccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccc"
     "dccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdc"),
    (20, 5,
     "ccccccccccccccddddededddddddeddddedddeddddedddededddddedddddeddeddddeddedddddeddedddddddeddedddddede"
     "dddddeedddddddeddddedddeddddeddeddedddddedddddddfdcddedddeddddeddeddddedddeddddedddddeddddeddddeddde"
     "ddddedddeddddedddedddedddeddddedddddeddddedddeddddeddeddeddddedddeddddedddeddddeddddedddeddddedddedd"
     "ddedddeddddeddddedddeddddedddeddddedddeddddedddeddddeddddedddeddddedddeddddedddeddddedddeddddedddded"
     "ddeddddedddeddddedddeddddeddddedddeddddedddeddddedddeddddedddeddddeddddedddeddddedddeddddedddedddded"
     "dddedddeddddedddeddddedddeddddedddeddddedddde",
     "ccccccccccccccccccdcdcccccccdccccdcccdccccdcccdcdcccccdcccccdccdccccdccdcccccdccdcccccccdccdcccccdcd"
     "cccccddcccccccdccccdcccdccccdccdccdcccccdcccccccecbccdcccdccccdccdccccdcccdccccdcccccdccccdccccdcccd"
     "ccccdcccdccccdcccdcccdcccdccccdcccccdccccdcccdccccdccdccdccccdcccdccccdcccdccccdccccdcccdccccdcccdcc"
     "ccdcccdccccdccccdcccdccccdcccdccccdcccdccccdcccdccccdccccdcccdccccdcccdccccdcccdccccdcccdccccdccccdc"
     "ccdccccdcccdccccdcccdccccdccccdcccdccccdcccdccccdcccdccccdcccdccccdccccdcccdccccdcccdccccdcccdccccdc"
     "cccdcccdccccdcccdccccdcccdccccdcccdccccdccccd"),
    (20, 5,
     "ccccccccccccdddefbhebddgdddeddgbdddeddedfedddbgdddeddfbeddgdfdcdddedddefddcdfddeddeddfbefbgddedfbdef"
     "ddedddgdbdfcfbdedfcfbfdeddedfdeaedfeddedfdcddfedddedddeddfcfddgbddchddcddehbddeddfcdfdedbfcfdbefdded"
     "ddefbdefddedddedfdcfdbgdgbdddfcfdbgbffcfbdefddedddgdbhdeddfedddedddeddfedddedddedddgdddedddedddefdde"
     "dddedddefddedddedddedfdedddedddeddfedddedddeddfedddedddedddgdddedddedddgdddedddedddefddedddedddedfde"
     "dddedddedfdedddedddeddfedddedddedddgdddedddedddgdddedddedddefddedddedddedfdedddedddedfdedddedddeddfe"
     "dddedddeddgdddedddedddefddedddedddedfdedddedd",
     "ccccccccccccdccddbedbccecccdccebcccdccdcddcccbecccdccdbdccecdcccccdcccddccccdccdccdccdbddbeccdcdbcdd"
     "ccdcccecbcdcdbcdcdcdbdcdccdcdcdadcddccdcdccccddcccdcccdccdcdccebcccecccccdebccdccdccdcdcbdcdcbddccdc"
     "ccddbcddccdcccdcdccdcbecebcccdcdcbebddcdbcddccdcccecbecdccddcccdcccdccddcccdcccdcccecccdcccdcccddccd"
     "cccdcccddccdcccdcccdcdcdcccdcccdccddcccdcccdccddcccdcccdcccecccdcccdcccecccdcccdcccddccdcccdcccdcdcd"
     "cccdcccdcdcdcccdcccdccddcccdcccdcccecccdcccdcccecccdcccdcccddccdcccdcccdcdcdcccdcccdcdcdcccdcccdccdd"
     "cccdcccdccecccdcccdcccddccdcccdcccdcdcdcccdcc"),
    (20, 5,
     "ccccccccccccccddddddeddddeddddeddddeddddedddeddddeddddeddddeddddeddddeddddedddeddddeddddeddddedddded"
     "dddedddeddddeddddeddddeddddeddddedddeddddeddddeddddeddddeddddeddddedddeddddeddddeddddeddddeddddeddde"
     "ddddeddddeddddeddddeddddedddeddddeddddeddddeddddeddddeddddedddeddddeddddeddddeddddeddddedddeddddeddd"
     "deddddeddddeddddedddeddddeddddeddddeddddeddddeddddedddeddddeddddeddddeddddeddddedddeddddeddddedddded"
     "dddeddddedddeddddeddddeddddeddddeddddeddddedddeddddeddddeddddeddddeddddedddeddddeddddeddddeddddedddd"
     "edddeddddeddddeddddeddddeddddedddeddddedddded",
     "ccccccccccccccccccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdc"
     "cccdcccdccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdccccdcccd"
     "ccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdccccdcccdccccdccc"
     "cdccccdccccdccccdcccdccccdccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdccccdcccdccccdccccdccccdc"
     "cccdccccdcccdccccdccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdcccc"
     "dcccdccccdccccdccccdccccdccccdcccdccccdccccdc"),
    (20, 5,
     "ccccccccccccccdddedddedddeddddedddedddedddedddedddedddeddfdedddedddedddedddedddedddeddddedddedddeddd"
     "edddgdddedddeddddedddedddedddedddedddedddeddddeddbedfdedddedddedddeddcdedddedddedddedddedddedddedddf"
     "edddedddedddedddedddedddeddddedddedddddddedddefddedddbdeddddedddeddddeddddedddeddddedddeddddefdddedd"
     "deddddeddddedddeddddedddeddddeddddedddedfddeddddedddeddddedddeddddeddddedddeddddeddddedfdeddddeddded"
     "dddeddddedddeddddeddddedddeddddeddfeddddeddddedddeddddedddeddddeddddedddeddddedddfedddeddddedddedddd"
     "eddddedddeddddeddddedddeddddgdddeddddeddddedd",
     "cccccccccccccccccdcccdcccdccccdcccdcccdcccdcccdcccdcccdccdcdcccdcccdcccdcccdcccdcccdccccdcccdcccdccc"
     "dcccecccdcccdccccdcccdcccdcccdcccdcccdcccdccccdccadcdcdcccdcccdcccdccbcdcccdcccdcccdcccdcccdcccdcccd"
     "dcccdcccdcccdcccdcccdcccdccccdcccdcccccccdcccddccdcccacdccccdcccdccccdccccdcccdccccdcccdccccddcccdcc"
     "cdccccdccccdcccdccccdcccdccccdccccdcccdcdccdccccdcccdccccdcccdccccdccccdcccdccccdccccdcdcdccccdcccdc"
     "cccdccccdcccdccccdccccdcccdccccdccddccccdccccdcccdccccdcccdccccdccccdcccdccccdcccddcccdccccdcccdcccc"
     "dccccdcccdccccdccccdcccdccccecccdccccdccccdcc"),
    (20, 5,
     "ccccccccccccccdddeddddddedddeddddedddeddddedddedddedddddefdddedddedddedddddedeceddddeddddedddedddded"
     "dddefddeddeceddecedddeddddeddddedddedddedddedecdedddgcedddeddddeddddeddeddeceddddedddedddddedddedddf"
     "edddeddeceddddedddeddddeddddedddeddddeddecedddgddddedddeddddedddeddddeddddedddeddddedddeddddefdddedd"
     "deddddeddddedddeddddedddeddddeddddedddedfddeddddedddeddddedddeddddeddddedddeddddeddddedfdeddddeddded"
     "dddeddddedddeddddeddddedddeddddeddfeddddeddddedddeddddedddeddddeddddedddeddddedddfedddeddddedddedddd"
     "eddddedddeddddeddddedddeddddgdddeddddeddddedd",
     "cccccccccccccccccdccccccdcccdccccdcccdccccdcccdcccdcccccddcccdcccdcccdcccccdcdbdccccdccccdcccdccccdc"
     "cccddccdccdbdccdbdcccdccccdccccdcccdcccdcccdcdbcdcccebdcccdccccdccccdccdccdbdccccdcccdcccccdcccdcccd"
     "dcccdccdbdccccdcccdccccdccccdcccdccccdccdbdccceccccdcccdccccdcccdccccdccccdcccdccccdcccdccccddcccdcc"
     "cdccccdccccdcccdccccdcccdccccdccccdcccdcdccdccccdcccdccccdcccdccccdccccdcccdccccdccccdcdcdccccdcccdc"
     "cccdccccdcccdccccdccccdcccdccccdccddccccdccccdcccdccccdcccdccccdccccdcccdccccdcccddcccdccccdcccdcccc"
     "dccccdcccdccccdccccdcccdccccecccdccccdccccdcc"),
    (20, 5,
     "ccccccccccccccdddedddedddeddddedddedddedddedddedddedddeddfdedddedddedddedddedddedddeddddedddedddeddd"
     "edddgdddedddeddddedddedddedddedddedddedddeddddeddbedfdedddedddedddeddcdedddedddddddddedececedddeeddf"
     "edddedddeddcedddedddedddeddddeddeeddddddcedddefecedddddeddddedddeddddeddddedddeddddedddeddddefdddedd"
     "deddddeddddedddeddddedddeddddeddddedddedfddeddddedddeddddedddeddddeddddedddeddddeddddedfdeddddeddded"
     "dddeddddedddeddddeddddedddeddddeddfeddddeddddedddeddddedddeddddeddddedddeddddedddfedddeddddedddedddd"
     "eddddedddeddddeddddedddeddddgdddeddddeddddedd",
     "cccccccccccccccccdcccdcccdccccdcccdcccdcccdcccdcccdcccdccdcdcccdcccdcccdcccdcccdcccdccccdcccdcccdccc"
     "dcccecccdcccdccccdcccdcccdcccdcccdcccdcccdccccdccadcdcdcccdcccdcccdccbcdcccdcccccccccdcdbdbdcccddccd"
     "dcccdcccdccbdcccdcccdcccdccccdccddccccccbdcccdddbdcccccdccccdcccdccccdccccdcccdccccdcccdccccddcccdcc"
     "cdccccdccccdcccdccccdcccdccccdccccdcccdcdccdccccdcccdccccdcccdccccdccccdcccdccccdccccdcdcdccccdcccdc"
     "cccdccccdcccdccccdccccdcccdccccdccddccccdccccdcccdccccdcccdccccdccccdcccdccccdcccddcccdccccdcccdcccc"
     "dccccdcccdccccdccccdcccdccccecccdccccdccccdcc"),
    (20, 5,
     "ccccccccccccccdededcdedddddddedddeddddedddedddeddddedddedfdddeddddedddeddddeddddeddeddedcedddedddded"
     "dddefddeddedddddeddddeddddeddddedddeddddedddeddddeddfdedddeddddedddedddeddddeddddeddddeddddedddedddg"
     "dddddedddeddddedddedddedddddedddeddddeddddededfddddedddeddddedddeddddeddddedddeddddedddeddddefdddedd"
     "deddddeddddedddeddddedddeddddeddddedddedfddeddddedddeddddedddeddddeddddedddeddddeddddedfdeddddeddded"
     "dddeddddedddeddddeddddedddeddddeddfeddddeddddedddeddddedddeddddeddddedddeddddedddfedddeddddedddedddd"
     "eddddedddeddddeddddedddeddddgdddeddddeddddedd",
     "cccccccccccccccdcdcbcdcccccccdcccdccccdcccdcccdccccdcccdcdcccdccccdcccdccccdccccdccdccdcbdcccdccccdc"
     "cccddccdccdcccccdccccdccccdccccdcccdccccdcccdccccdccdcdcccdccccdcccdcccdccccdccccdccccdccccdcccdccce"
     "cccccdcccdccccdcccdcccdcccccdcccdccccdccccdcdcdccccdcccdccccdcccdccccdccccdcccdccccdcccdccccddcccdcc"
     "cdccccdccccdcccdccccdcccdccccdccccdcccdcdccdccccdcccdccccdcccdccccdccccdcccdccccdccccdcdcdccccdcccdc"
     "cccdccccdcccdccccdccccdcccdccccdccddccccdccccdcccdccccdcccdccccdccccdcccdccccdcccddcccdccccdcccdcccc"
     "dccccdcccdccccdccccdcccdccccecccdccccdccccdcc"),
    (20, 5,
     "ccccccccccccccddddfbdedfdbeddfbeddfdcdddfcdddfebdddgbdddgddbdefbddefdbdedfdbedfdcdddfebddffbdddgbddd"
     "gdbddefbddefbddedfbdedfbdedfdbeddfbeddfdcdddfcdddfebfbdgbfbdgdbfbefbfbefddbedfddcdfddcddfdebdfdcdddf"
     "edbdfebdddgbfbdgddbdefbfbefddbedfbdedfddcddfdcddfeddbhddddeddddeddddedddeddddefdddeddddedddeddddeddd"
     "deddddedddeddddeddddeddddeddddedddeddddeddddeddddedddeddddeddddeddddedddeddddeddddeddddedddeddddeddd"
     "deddddedddeddddeddddeddddeddddedddeddddeddddeddddedddeddddeddddefdddedddeddddeddddeddddedddeddddeddd"
     "deddddedddeddddeddddeddddeddddedddeddddedddde",
     "ccccccccccccccccccdbcdcdcbdccdbdccdcccccdccccddbcccebccceccbcddbccddcbcdcdcbdcdcccccddbccdebcccebccc"
     "ecbccddbccddbccdcdbcdcdbcdcdcbdccdbdccdcccccdccccddbdbcebdbcecbdbddbdbddccbdcdccccdcccccdcdbcdcccccd"
     "dcbcddbcccebdbceccbcddbdbddccbdcdbcdcdcccccdccccddccbfccccdccccdccccdcccdccccddcccdccccdcccdccccdccc"
     "cdccccdcccdccccdccccdccccdccccdcccdccccdccccdccccdcccdccccdccccdccccdcccdccccdccccdccccdcccdccccdccc"
     "cdccccdcccdccccdccccdccccdccccdcccdccccdccccdccccdcccdccccdccccddcccdcccdccccdccccdccccdcccdccccdccc"
     "cdccccdcccdccccdccccdccccdccccdcccdccccdccccd"),
)
#: (font, bold, italic) -> the table measured for it.
_OWNER: dict[tuple[str, bool, bool], int] = {
    ('aptos', False, False): 0,
    ('aptos', False, True): 0,
    ('aptos', True, False): 0,
    ('aptos', True, True): 0,
    ('aptos display', False, False): 0,
    ('aptos display', False, True): 0,
    ('aptos display', True, False): 0,
    ('aptos display', True, True): 0,
    ('aptos narrow', False, False): 0,
    ('aptos narrow', False, True): 0,
    ('aptos narrow', True, False): 0,
    ('aptos narrow', True, True): 0,
    ('arial', False, False): 1,
    ('arial', False, True): 3,
    ('arial', True, False): 2,
    ('arial', True, True): 4,
    ('calibri', False, False): 5,
    ('calibri', False, True): 5,
    ('calibri', True, False): 5,
    ('calibri', True, True): 5,
    ('calibri light', False, False): 5,
    ('calibri light', False, True): 5,
    ('calibri light', True, False): 5,
    ('calibri light', True, True): 5,
    ('cambria', False, False): 6,
    ('cambria', False, True): 6,
    ('cambria', True, False): 6,
    ('cambria', True, True): 6,
    ('consolas', False, False): 7,
    ('consolas', False, True): 7,
    ('consolas', True, False): 7,
    ('consolas', True, True): 7,
    ('courier new', False, False): 8,
    ('courier new', False, True): 10,
    ('courier new', True, False): 9,
    ('courier new', True, True): 9,
    ('georgia', False, False): 11,
    ('georgia', False, True): 11,
    ('georgia', True, False): 11,
    ('georgia', True, True): 11,
    ('segoe ui', False, False): 12,
    ('segoe ui', False, True): 12,
    ('segoe ui', True, False): 12,
    ('segoe ui', True, True): 12,
    ('tahoma', False, False): 13,
    ('tahoma', False, True): 13,
    ('tahoma', True, False): 13,
    ('tahoma', True, True): 13,
    ('times new roman', False, False): 14,
    ('times new roman', False, True): 16,
    ('times new roman', True, False): 15,
    ('times new roman', True, True): 17,
    ('verdana', False, False): 18,
    ('verdana', False, True): 18,
    ('verdana', True, False): 18,
    ('verdana', True, True): 18,
}


@cache
def _decoded(index: int) -> tuple[tuple[int, ...], tuple[int, ...]]:
    first_row, first_descent, row_steps, descent_steps = _TABLES[index]
    return _run(first_row, row_steps), _run(first_descent, descent_steps)


def _run(first: int, steps: str) -> tuple[int, ...]:
    values = [first]
    for step in steps:
        values.append(values[-1] + _ALPHABET.index(step) + _LOWEST)
    return tuple(values)


def table_of(font: str, bold: bool, italic: bool) -> int | None:
    """Which measured table a font and style use, or None when it was not measured."""
    return _OWNER.get((font.lower(), bold, italic))


def row_of(table: int, pixels: int) -> tuple[int, int]:
    """The row's height in pixels and its descent in twips, at a pixel size from 1 to MOST_PIXELS."""
    rows, descents = _decoded(table)
    return rows[pixels - 1], descents[pixels - 1]
