"""How tall a font makes a row, as Excel measures it on a 96-DPI display.

Generated by scripts/bake_font_rows.py from tests/fixtures/font_rows.json,
which scripts/measure_font_heights.py measured in live Excel. For each font
and style, at every pixel size from 1 to 546 (409.5pt), the table holds
the height in pixels of a row whose only font besides the Normal one it
is, and the descent Excel writes for that row, in twips; then the same
for a row the font has to itself, which a small font leaves shorter than
the standard row. The heights follow each font's hinted metrics
irregularly enough that no formula over the font's own tables reproduces
them. Do not edit by hand.
"""

from __future__ import annotations

from functools import cache

MOST_PIXELS = 546
#: One letter per step from one pixel size to the next; "a" is -2.
_ALPHABET = "abcdefghijklmnopqrstuvwxyz"
_LOWEST = -2
#: Each table: the row heights and descents beside the Normal font, then
#: the row heights and descents alone, each as its first value and steps.
_TABLES: tuple[tuple[tuple[int, str], ...], ...] = (
    (
        (20,
        "ccccccccccccccdedddeddedddeddedddedddeddedddedddedfedddedddeddedddeddedddedddeddedddedddeddedddeddde"
        "ddedddeddedddedddeddedddedddeddedddedddeddedddeddeddfedddeddedddedddeddedddedddeddedddeddedddedddedd"
        "edddedddeddedddedddeddedddeddedddedddeddedddedddeddeddfedddeddedddedddeddedddeddedddedddeddedddeddde"
        "ddedddedddeddedddeddedddedddeddedddedddeddedddedddeddedddgddedddedddeddedddedddeddedddedddeddedddedd"
        "edddedddeddedddedddeddedddedddeddedddeddedddedddeddedddedddgddedddedddeddedddeddedddedddeddedddeddde"
        "ddedddedddeddedddedddeddedddeddedddedddeddedd"),
        (5,
        "cccccccccccccccdcccdccdcccdccdcccdcccdccdcccdcccdcddcccdcccdccdcccdccdcccdcccdccdcccdcccdccdcccdcccd"
        "ccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccdccdccddcccdccdcccdcccdccdcccdcccdccdcccdccdcccdcccdcc"
        "dcccdcccdccdcccdcccdccdcccdccdcccdcccdccdcccdcccdccdccddcccdccdcccdcccdccdcccdccdcccdcccdccdcccdcccd"
        "ccdcccdcccdccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdccceccdcccdcccdccdcccdcccdccdcccdcccdccdcccdcc"
        "dcccdcccdccdcccdcccdccdcccdcccdccdcccdccdcccdcccdccdcccdccceccdcccdcccdccdcccdccdcccdcccdccdcccdcccd"
        "ccdcccdcccdccdcccdcccdccdcccdccdcccdcccdccdcc"),
        (7,
        "ccddcecddededddedddeddedddeddedddedddeddedddedddedfedddedddeddedddeddedddedddeddedddedddeddedddeddde"
        "ddedddeddedddedddeddedddedddeddedddedddeddedddeddeddfedddeddedddedddeddedddedddeddedddeddedddedddedd"
        "edddedddeddedddedddeddedddeddedddedddeddedddedddeddeddfedddeddedddedddeddedddeddedddedddeddedddeddde"
        "ddedddedddeddedddeddedddedddeddedddedddeddedddedddeddedddgddedddedddeddedddedddeddedddedddeddedddedd"
        "edddedddeddedddedddeddedddedddeddedddeddedddedddeddedddedddgddedddedddeddedddeddedddedddeddedddeddde"
        "ddedddedddeddedddedddeddedddeddedddedddeddedd"),
        (3,
        "cccccccccdcdcccdcccdccdcccdccdcccdcccdccdcccdcccdcddcccdcccdccdcccdccdcccdcccdccdcccdcccdccdcccdcccd"
        "ccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccdccdccddcccdccdcccdcccdccdcccdcccdccdcccdccdcccdcccdcc"
        "dcccdcccdccdcccdcccdccdcccdccdcccdcccdccdcccdcccdccdccddcccdccdcccdcccdccdcccdccdcccdcccdccdcccdcccd"
        "ccdcccdcccdccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdccceccdcccdcccdccdcccdcccdccdcccdcccdccdcccdcc"
        "dcccdcccdccdcccdcccdccdcccdcccdccdcccdccdcccdcccdccdcccdccceccdcccdcccdccdcccdccdcccdcccdccdcccdcccd"
        "ccdcccdcccdccdcccdcccdccdcccdccdcccdcccdccdcc"),
    ),
    (
        (20,
        "ccccccccccccccdddddeddecedddeddddeddeddddedddddeddedddeddddddedddeddeddddddgdddeddedddedcedddeddeddd"
        "eddecddeddedddeddeddddddedddeddedddefcedddeddedddcededdddddedddeeddddddddddeddeeddddddeddddddededfed"
        "ddddddddeeddedddddddededdddddeddedddeddddddeddeddddedcddedfdeddddeddddeddddedddeddddeddddedddedddded"
        "dddeddddedddeddddedfddedddeddddeddddeddddedddeddddeddddedddeddddeddddeddddedddeddfdeddddeddddedddedd"
        "ddeddddedddeddddeddddeddddedddeddddeddddedfdeddddeddddeddddedddeddddeddddedddeddddeddddeddddedddeddd"
        "dedfddedddeddddeddddeddddedddeddddeddddedddde"),
        (5,
        "cccccccccccccccccccdccdbdcccdccccdccdccccdcccccdccdcccdccccccdcccdccdccccccecccdccdcccdcbdcccdccdccc"
        "dccdbccdccdcccdccdccccccdcccdccdcccddbdcccdccdcccbdcdccccccdcccddccccccccccdccddccccccdccccccdcdcddc"
        "ccccccccddccdcccccccdcdccccccdccdcccdccccccdccdccccdcbccdcdcdccccdccccdccccdcccdccccdccccdcccdccccdc"
        "cccdccccdcccdccccdcdccdcccdccccdccccdccccdcccdccccdccccdcccdccccdccccdccccdcccdccdcdccccdccccdcccdcc"
        "ccdccccdcccdccccdccccdccccdcccdccccdccccdcdcdccccdccccdccccdcccdccccdccccdcccdccccdccccdccccdcccdccc"
        "cdcdccdcccdccccdccccdccccdcccdccccdccccdccccd"),
        (7,
        "ccddcecddedddddedddeddecedddeddddeddeddddedddddeddedddeddddddedddeddeddddddgdddeddedddedcedddeddeddd"
        "eddecddeddedddeddeddddddedddeddedddefcedddeddedddcededdddddedddeeddddddddddeddeeddddddeddddddededfed"
        "ddddddddeeddedddddddededdddddeddedddeddddddeddeddddedcddedfdeddddeddddeddddedddeddddeddddedddedddded"
        "dddeddddedddeddddedfddedddeddddeddddeddddedddeddddeddddedddeddddeddddeddddedddeddfdeddddeddddedddedd"
        "ddeddddedddeddddeddddeddddedddeddddeddddedfdeddddeddddeddddedddeddddeddddedddeddddeddddeddddedddeddd"
        "dedfddedddeddddeddddeddddedddeddddeddddedddde"),
        (3,
        "cccccccccdcccccdcccdccdbdcccdccccdccdccccdcccccdccdcccdccccccdcccdccdccccccecccdccdcccdcbdcccdccdccc"
        "dccdbccdccdcccdccdccccccdcccdccdcccddbdcccdccdcccbdcdccccccdcccddccccccccccdccddccccccdccccccdcdcddc"
        "ccccccccddccdcccccccdcdccccccdccdcccdccccccdccdccccdcbccdcdcdccccdccccdccccdcccdccccdccccdcccdccccdc"
        "cccdccccdcccdccccdcdccdcccdccccdccccdccccdcccdccccdccccdcccdccccdccccdccccdcccdccdcdccccdccccdcccdcc"
        "ccdccccdcccdccccdccccdccccdcccdccccdccccdcdcdccccdccccdccccdcccdccccdccccdcccdccccdccccdccccdcccdccc"
        "cdcdccdcccdccccdccccdccccdcccdccccdccccdccccd"),
    ),
    (
        (20,
        "ccccccccccccccddddedddeddeddddddeeddddddeeddddddeddeddddedddeddeddddddeedddfdddfcdddddedddedddeddddd"
        "ededdddddeddeddddeddddeddedddddededdfdddedddeddedcdddddfddddcdeddeecddedddddededddddeddedddddedddfed"
        "dedddddededdddddeddeddddedddddededdddddededddddeddddecddedfdeddddeddddeddddedddeddddeddddedddedddded"
        "dddeddddedddeddddedfddedddeddddeddddeddddedddeddddeddddedddeddddeddddeddddedddeddfdeddddeddddedddedd"
        "ddeddddedddeddddeddddeddddedddeddddeddddedfdeddddeddddeddddedddeddddeddddedddeddddeddddeddddedddeddd"
        "dedfddedddeddddeddddeddddedddeddddeddddedddde"),
        (5,
        "ccccccccccccccccccdcccdccdccccccddccccccddccccccdccdccccdcccdccdccccccddcccdcccebcccccdcccdcccdccccc"
        "dcdccccccdccdccccdccccdccdcccccdcdccdcccdcccdccdcbccccceccccbcdccddbccdcccccdcdcccccdccdcccccdcccddc"
        "cdcccccdcdccccccdccdccccdcccccdcdccccccdcdcccccdccccdbccdcdcdccccdccccdccccdcccdccccdccccdcccdccccdc"
        "cccdccccdcccdccccdcdccdcccdccccdccccdccccdcccdccccdccccdcccdccccdccccdccccdcccdccdcdccccdccccdcccdcc"
        "ccdccccdcccdccccdccccdccccdcccdccccdccccdcdcdccccdccccdccccdcccdccccdccccdcccdccccdccccdccccdcccdccc"
        "cdcdccdcccdccccdccccdccccdcccdccccdccccdccccd"),
        (7,
        "ccddcecddedddeddddedddeddeddddddeeddddddeeddddddeddeddddedddeddeddddddeedddfdddfcdddddedddedddeddddd"
        "ededdddddeddeddddeddddeddedddddededdfdddedddeddedcdddddfddddcdeddeecddedddddededddddeddedddddedddfed"
        "dedddddededdddddeddeddddedddddededdddddededddddeddddecddedfdeddddeddddeddddedddeddddeddddedddedddded"
        "dddeddddedddeddddedfddedddeddddeddddeddddedddeddddeddddedddeddddeddddeddddedddeddfdeddddeddddedddedd"
        "ddeddddedddeddddeddddeddddedddeddddeddddedfdeddddeddddeddddedddeddddeddddedddeddddeddddeddddedddeddd"
        "dedfddedddeddddeddddeddddedddeddddeddddedddde"),
        (3,
        "cccccccccdcccdccccdcccdccdccccccddccccccddccccccdccdccccdcccdccdccccccddcccdcccebcccccdcccdcccdccccc"
        "dcdccccccdccdccccdccccdccdcccccdcdccdcccdcccdccdcbccccceccccbcdccddbccdcccccdcdcccccdccdcccccdcccddc"
        "cdcccccdcdccccccdccdccccdcccccdcdccccccdcdcccccdccccdbccdcdcdccccdccccdccccdcccdccccdccccdcccdccccdc"
        "cccdccccdcccdccccdcdccdcccdccccdccccdccccdcccdccccdccccdcccdccccdccccdccccdcccdccdcdccccdccccdcccdcc"
        "ccdccccdcccdccccdccccdccccdcccdccccdccccdcdcdccccdccccdccccdcccdccccdccccdcccdccccdccccdccccdcccdccc"
        "cdcdccdcccdccccdccccdccccdcccdccccdccccdccccd"),
    ),
    (
        (20,
        "ccccccccccccccddedddeddddddeddeddddedddedddeddddddfddddddeddddedecddeddedddfdddededdeddddddddfdddedd"
        "ddddddddededddddddeddddededddddeddddgdddedddeddddeddddddeddeddeddddddeddddddfdddddeddddddedddeeddfdd"
        "ddeddddeddeddddeddddeddddddeedddeddddddddeddeeddddddddddedfdeddddeddddeddddedddeddddeddddedddedddded"
        "dddeddddedddeddddedfddedddeddddeddddeddddedddeddddeddddedddeddddeddddeddddedddeddfdeddddeddddedddedd"
        "ddeddddedddeddddeddddeddddedddeddddeddddedfdeddddeddddeddddedddeddddeddddedddeddddeddddeddddedddeddd"
        "dedfddedddeddddeddddeddddedddeddddeddddedddde"),
        (5,
        "ccccccccccccccccdcccdccccccdccdccccdcccdcccdcccccceccccccdccccdcdbccdccdcccdcccdcdccdccccccccecccdcc"
        "ccccccccdcdcccccccdccccdcdcccccdccccecccdcccdccccdccccccdccdccdccccccdccccccecccccdccccccdcccddccdcc"
        "ccdccccdccdccccdccccdccccccddcccdccccccccdccddccccccccccdcdcdccccdccccdccccdcccdccccdccccdcccdccccdc"
        "cccdccccdcccdccccdcdccdcccdccccdccccdccccdcccdccccdccccdcccdccccdccccdccccdcccdccdcdccccdccccdcccdcc"
        "ccdccccdcccdccccdccccdccccdcccdccccdccccdcdcdccccdccccdccccdcccdccccdccccdcccdccccdccccdccccdcccdccc"
        "cdcdccdcccdccccdccccdccccdcccdccccdccccdccccd"),
        (7,
        "ccddcecddedddddeedddeddddddeddeddddedddedddeddddddfddddddeddddedecddeddedddfdddededdeddddddddfdddedd"
        "ddddddddededddddddeddddededddddeddddgdddedddeddddeddddddeddeddeddddddeddddddfdddddeddddddedddeeddfdd"
        "ddeddddeddeddddeddddeddddddeedddeddddddddeddeeddddddddddedfdeddddeddddeddddedddeddddeddddedddedddded"
        "dddeddddedddeddddedfddedddeddddeddddeddddedddeddddeddddedddeddddeddddeddddedddeddfdeddddeddddedddedd"
        "ddeddddedddeddddeddddeddddedddeddddeddddedfdeddddeddddeddddedddeddddeddddedddeddddeddddeddddedddeddd"
        "dedfddedddeddddeddddeddddedddeddddeddddedddde"),
        (3,
        "cccccccccdcccccddcccdccccccdccdccccdcccdcccdcccccceccccccdccccdcdbccdccdcccdcccdcdccdccccccccecccdcc"
        "ccccccccdcdcccccccdccccdcdcccccdccccecccdcccdccccdccccccdccdccdccccccdccccccecccccdccccccdcccddccdcc"
        "ccdccccdccdccccdccccdccccccddcccdccccccccdccddccccccccccdcdcdccccdccccdccccdcccdccccdccccdcccdccccdc"
        "cccdccccdcccdccccdcdccdcccdccccdccccdccccdcccdccccdccccdcccdccccdccccdccccdcccdccdcdccccdccccdcccdcc"
        "ccdccccdcccdccccdccccdccccdcccdccccdccccdcdcdccccdccccdccccdcccdccccdccccdcccdccccdccccdccccdcccdccc"
        "cdcdccdcccdccccdccccdccccdcccdccccdccccdccccd"),
    ),
    (
        (20,
        "ccccccccccccccdddeddddeceddeddddedddedddeddddddededdddedddddededddddedddeddfdeddddeddeddddddededdddd"
        "eddecededdddddeddeddddedddddededdddefddedddddedddcededdddddeceddddfcdddedddeddddedddedddddedddeddgdd"
        "ddddeddeddddeddddeddeddddddededddddeddddededddddddedecddedfdeddddeddddeddddedddeddddeddddedddedddded"
        "dddeddddedddeddddedfddedddeddddeddddeddddedddeddddeddddedddeddddeddddeddddedddeddfdeddddeddddedddedd"
        "ddeddddedddeddddeddddeddddedddeddddeddddedfdeddddeddddeddddedddeddddeddddedddeddddeddddeddddedddeddd"
        "dedfddedddeddddeddddeddddedddeddddeddddedddde"),
        (5,
        "cccccccccccccccccdccccdbdccdccccdcccdcccdccccccdcdccccdcccccdcdcccccdcccdccdcdccccdccdccccccdcdccccc"
        "dccdbdcdccccccdccdccccdcccccdcdccccddccdcccccdcccbdcdccccccdbdccccebcccdcccdccccdcccdcccccdcccdccecc"
        "ccccdccdccccdccccdccdccccccdcdcccccdccccdcdcccccccdcdbccdcdcdccccdccccdccccdcccdccccdccccdcccdccccdc"
        "cccdccccdcccdccccdcdccdcccdccccdccccdccccdcccdccccdccccdcccdccccdccccdccccdcccdccdcdccccdccccdcccdcc"
        "ccdccccdcccdccccdccccdccccdcccdccccdccccdcdcdccccdccccdccccdcccdccccdccccdcccdccccdccccdccccdcccdccc"
        "cdcdccdcccdccccdccccdccccdcccdccccdccccdccccd"),
        (7,
        "ccddcecdddeddddededdddeceddeddddedddedddeddddddededdddedddddededddddedddeddfdeddddeddeddddddededdddd"
        "eddecededdddddeddeddddedddddededdddefddedddddedddcededdddddeceddddfcdddedddeddddedddedddddedddeddgdd"
        "ddddeddeddddeddddeddeddddddededddddeddddededddddddedecddedfdeddddeddddeddddedddeddddeddddedddedddded"
        "dddeddddedddeddddedfddedddeddddeddddeddddedddeddddeddddedddeddddeddddeddddedddeddfdeddddeddddedddedd"
        "ddeddddedddeddddeddddeddddedddeddddeddddedfdeddddeddddeddddedddeddddeddddedddeddddeddddeddddedddeddd"
        "dedfddedddeddddeddddeddddedddeddddeddddedddde"),
        (3,
        "ccccccccccdccccdcdccccdbdccdccccdcccdcccdccccccdcdccccdcccccdcdcccccdcccdccdcdccccdccdccccccdcdccccc"
        "dccdbdcdccccccdccdccccdcccccdcdccccddccdcccccdcccbdcdccccccdbdccccebcccdcccdccccdcccdcccccdcccdccecc"
        "ccccdccdccccdccccdccdccccccdcdcccccdccccdcdcccccccdcdbccdcdcdccccdccccdccccdcccdccccdccccdcccdccccdc"
        "cccdccccdcccdccccdcdccdcccdccccdccccdccccdcccdccccdccccdcccdccccdccccdccccdcccdccdcdccccdccccdcccdcc"
        "ccdccccdcccdccccdccccdccccdcccdccccdccccdcdcdccccdccccdccccdcccdccccdccccdcccdccccdccccdccccdcccdccc"
        "cdcdccdcccdccccdccccdccccdcccdccccdccccdccccd"),
    ),
    (
        (20,
        "ccccccccccccccdedddedddeddedddedddedddeddedddedddeddedddedddedddeddedddedddedddeddedddedddeddedddedd"
        "dedddeddedddedddedddeddedddedddeddedddedddedddeddedddedddeddedddedddedddeddedddedddedddeddedddeddded"
        "dedddedddedddeddedddedddedddeddedddedddeddedddedddedddeddedddedddeddedddedddedddeddedddedddedddedded"
        "ddedddeddedddedddedddeddedddedddeddedddedddedddeddedddedddedddeddedddedddeddedddedddedddeddedddeddde"
        "dddeddedddedddeddedddedddedddeddedddedddeddedddedddedddeddedddedddedddeddedddedddeddedddedddedddedde"
        "dddedddeddedddedddedddeddedddedddedddeddeddde"),
        (5,
        "cccccccccccccccdcccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcc"
        "cdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccdcccdcccdcccdccdcccdcccdc"
        "cdcccdcccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccdcccdcccdcccdccdc"
        "ccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccdcccdcccd"
        "cccdccdcccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccd"
        "cccdcccdccdcccdcccdcccdccdcccdcccdcccdccdcccd"),
        (7,
        "ccddcecddeddeddedddedddeddedddedddedddeddedddedddeddedddedddedddeddedddedddedddeddedddedddeddedddedd"
        "dedddeddedddedddedddeddedddedddeddedddedddedddeddedddedddeddedddedddedddeddedddedddedddeddedddeddded"
        "dedddedddedddeddedddedddedddeddedddedddeddedddedddedddeddedddedddeddedddedddedddeddedddedddedddedded"
        "ddedddeddedddedddedddeddedddedddeddedddedddedddeddedddedddedddeddedddedddeddedddedddedddeddedddeddde"
        "dddeddedddedddeddedddedddedddeddedddedddeddedddedddedddeddedddedddedddeddedddedddeddedddedddedddedde"
        "dddedddeddedddedddedddeddedddedddedddeddeddde"),
        (3,
        "cccccccccdccdccdcccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcc"
        "cdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccdcccdcccdcccdccdcccdcccdc"
        "cdcccdcccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccdcccdcccdcccdccdc"
        "ccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccdcccdcccd"
        "cccdccdcccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccdcccdcccdcccdccdcccdcccdccdcccdcccdcccdccd"
        "cccdcccdccdcccdcccdcccdccdcccdcccdcccdccdcccd"),
    ),
    (
        (20,
        "ccccccccccccccdddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddedddd"
        "edddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddedddde"
        "dddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddedddded"
        "ddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedd"
        "deddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddeddd"
        "eddddedddeddddedddeddddedddeddddedddeddddeddd"),
        (5,
        "cccccccccccccccccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdcccc"
        "dcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccd"
        "cccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdc"
        "ccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcc"
        "cdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdccc"
        "dccccdcccdccccdcccdccccdcccdccccdcccdccccdccc"),
        (7,
        "ccddcecdddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddedddd"
        "edddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddedddde"
        "dddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddedddded"
        "ddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedd"
        "deddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddedddeddddeddd"
        "eddddedddeddddedddeddddedddeddddedddeddddeddd"),
        (3,
        "ccccccccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdcccc"
        "dcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccd"
        "cccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdc"
        "ccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcc"
        "cdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdcccdccccdccc"
        "dccccdcccdccccdcccdccccdcccdccccdcccdccccdccc"),
    ),
    (
        (20,
        "ccccccccccccccddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddeddd"
        "edddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddeddd"
        "edddedddedddedddedddedddedddedddedddedddedddedddedddeddedddedddedddedddedddedddedddedddedddedddeddde"
        "dddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddeddde"
        "dddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddeddde"
        "dddedddeddedddedddedddedddedddedddedddedddedd"),
        (5,
        "ccccccccccccccccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdccc"
        "dcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdccc"
        "dcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccd"
        "cccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccd"
        "cccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccd"
        "cccdcccdccdcccdcccdcccdcccdcccdcccdcccdcccdcc"),
        (7,
        "ccddcecddeddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddeddd"
        "edddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddeddd"
        "edddedddedddedddedddedddedddedddedddedddedddedddedddeddedddedddedddedddedddedddedddedddedddedddeddde"
        "dddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddeddde"
        "dddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddedddeddde"
        "dddedddeddedddedddedddedddedddedddedddedddedd"),
        (3,
        "cccccccccdccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdccc"
        "dcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdccc"
        "dcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccd"
        "cccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccd"
        "cccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccdcccd"
        "cccdcccdccdcccdcccdcccdcccdcccdcccdcccdcccdcc"),
    ),
    (
        (20,
        "ccccccccccccccdedddeddedddedddeddedddeddedddedddeddedddedddeddedddedddeddedddedddeddedddedddeddeddde"
        "dddeddedddeddedddedddeddedddedddeddedddedddeddedddedddeddedddedddeddedddedddeddedddeddedddedddeddedd"
        "dedddeddedddedddeddedddedddeddedddedddeddedddedddeddekdddeddeddedddeddeddedddeddeddedddeddeddedddedd"
        "eddedddeddeddedddeddeddedddeddeddedddeddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddeddd"
        "eddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddeddd"
        "eddeddedddeddeddedddeddeddedddeddeddedddedded"),
        (5,
        "cccccccccccccccdcccdccdcccdcccdccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccd"
        "cccdccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccdccdcccdcccdccdcc"
        "cdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdjcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdcc"
        "dccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccc"
        "dccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccc"
        "dccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdc"),
        (7,
        "ccddcecddededddedddeddedddedddeddedddeddedddedddeddedddedddeddedddedddeddedddedddeddedddedddeddeddde"
        "dddeddedddeddedddedddeddedddedddeddedddedddeddedddedddeddedddedddeddedddedddeddedddeddedddedddeddedd"
        "dedddeddedddedddeddedddedddeddedddedddeddedddedddeddekdddeddeddedddeddeddedddeddeddedddeddeddedddedd"
        "eddedddeddeddedddeddeddedddeddeddedddeddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddeddd"
        "eddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddeddd"
        "eddeddedddeddeddedddeddeddedddeddeddedddedded"),
        (3,
        "cccccccccdcdcccdcccdccdcccdcccdccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccd"
        "cccdccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccdccdcccdcccdccdcc"
        "cdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdcccdcccdccdjcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdcc"
        "dccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccc"
        "dccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccc"
        "dccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdc"),
    ),
    (
        (20,
        "cccccccccccccddddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddedd"
        "eddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddedd"
        "eddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddedd"
        "eddedddeddeddedddeddeddedddeddeddedddeddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddeddd"
        "eddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddeddd"
        "eddeddedddeddeddedddeddeddedddeddeddedddedded"),
        (5,
        "cccccccccccccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdcc"
        "dccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdcc"
        "dccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdcc"
        "dccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccc"
        "dccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccc"
        "dccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdc"),
        (7,
        "ccddcecddeeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddedd"
        "eddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddedd"
        "eddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddedd"
        "eddedddeddeddedddeddeddedddeddeddedddeddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddeddd"
        "eddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddeddd"
        "eddeddedddeddeddedddeddeddedddeddeddedddedded"),
        (3,
        "cccccccccddccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdcc"
        "dccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdcc"
        "dccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdcc"
        "dccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccc"
        "dccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccc"
        "dccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdc"),
    ),
    (
        (20,
        "cccccccccccccdddddedddedddeddddedddeeddeddddedddedddedddeddddfdddedddeddddedddedddedddfddddedddeddde"
        "ddddedddeddeeddddedddedddedddeddddedededddeddddedddedddedddededdedddedddeddddedddedddeedddedddeddded"
        "ddeddddedddfdddeddddedddedddedddedddeedddedddeddddeddldddeddeddedddeddeddedddeddeddedddeddeddedddedd"
        "eddedddeddeddedddeddeddedddeddeddedddeddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddeddd"
        "eddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddeddd"
        "eddeddedddeddeddedddeddeddedddeddeddedddedded"),
        (5,
        "cccccccccccccdccccdcccdcccdccccdcccddccdccccdcccdcccdcccdccccecccdcccdccccdcccdcccdccceccccdcccdcccd"
        "ccccdcccdccddccccdcccdcccdcccdccccdcdcdcccdccccdcccdcccdcccdcdccdcccdcccdccccdcccdcccddcccdcccdcccdc"
        "ccdccccdcccecccdccccdcccdcccdcccdcccddcccdcccdccccdcckcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdcc"
        "dccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccc"
        "dccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccc"
        "dccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdc"),
        (7,
        "ccddcecddfdddeddddedddedddeddddedddeeddeddddedddedddedddeddddfdddedddeddddedddedddedddfddddedddeddde"
        "ddddedddeddeeddddedddedddedddeddddedededddeddddedddedddedddededdedddedddeddddedddedddeedddedddeddded"
        "ddeddddedddfdddeddddedddedddedddedddeedddedddeddddeddldddeddeddedddeddeddedddeddeddedddeddeddedddedd"
        "eddedddeddeddedddeddeddedddeddeddedddeddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddeddd"
        "eddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddedddeddeddeddd"
        "eddeddedddeddeddedddeddeddedddeddeddedddedded"),
        (3,
        "cccccccccecccdccccdcccdcccdccccdcccddccdccccdcccdcccdcccdccccecccdcccdccccdcccdcccdccceccccdcccdcccd"
        "ccccdcccdccddccccdcccdcccdcccdccccdcdcdcccdccccdcccdcccdcccdcdccdcccdcccdccccdcccdcccddcccdcccdcccdc"
        "ccdccccdcccecccdccccdcccdcccdcccdcccddcccdcccdccccdcckcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdcc"
        "dccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccc"
        "dccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdccdccc"
        "dccdccdcccdccdccdcccdccdccdcccdccdccdcccdccdc"),
    ),
    (
        (20,
        "ccccccccccccccddddededddddddeddddedddeddddedddededddddedddddeddeddddeddedddddeddedddddddeddedddddede"
        "dddddeedddddddeddddedddeddddeddeddedddddedddddddfdcddedddeddddeddeddddedddeddddedddddeddddeddddeddde"
        "ddddedddeddddedddedddedddeddddedddddeddddedddeddddeddeddeddddedddeddddedddeddddeddddedddeddddedddedd"
        "ddedddeddddeddddedddeddddedddeddddedddeddddedddeddddeddddedddeddddedddeddddedddeddddedddeddddedddded"
        "ddeddddedddeddddedddeddddeddddedddeddddedddeddddedddeddddedddeddddeddddedddeddddedddeddddedddedddded"
        "dddedddeddddedddeddddedddeddddedddeddddedddde"),
        (5,
        "ccccccccccccccccccdcdcccccccdccccdcccdccccdcccdcdcccccdcccccdccdccccdccdcccccdccdcccccccdccdcccccdcd"
        "cccccddcccccccdccccdcccdccccdccdccdcccccdcccccccecbccdcccdccccdccdccccdcccdccccdcccccdccccdccccdcccd"
        "ccccdcccdccccdcccdcccdcccdccccdcccccdccccdcccdccccdccdccdccccdcccdccccdcccdccccdccccdcccdccccdcccdcc"
        "ccdcccdccccdccccdcccdccccdcccdccccdcccdccccdcccdccccdccccdcccdccccdcccdccccdcccdccccdcccdccccdccccdc"
        "ccdccccdcccdccccdcccdccccdccccdcccdccccdcccdccccdcccdccccdcccdccccdccccdcccdccccdcccdccccdcccdccccdc"
        "cccdcccdccccdcccdccccdcccdccccdcccdccccdccccd"),
        (7,
        "ccddcecddedddddeddededddddddeddddedddeddddedddededddddedddddeddeddddeddedddddeddedddddddeddedddddede"
        "dddddeedddddddeddddedddeddddeddeddedddddedddddddfdcddedddeddddeddeddddedddeddddedddddeddddeddddeddde"
        "ddddedddeddddedddedddedddeddddedddddeddddedddeddddeddeddeddddedddeddddedddeddddeddddedddeddddedddedd"
        "ddedddeddddeddddedddeddddedddeddddedddeddddedddeddddeddddedddeddddedddeddddedddeddddedddeddddedddded"
        "ddeddddedddeddddedddeddddeddddedddeddddedddeddddedddeddddedddeddddeddddedddeddddedddeddddedddedddded"
        "dddedddeddddedddeddddedddeddddedddeddddedddde"),
        (3,
        "cccccccccdcccccdccdcdcccccccdccccdcccdccccdcccdcdcccccdcccccdccdccccdccdcccccdccdcccccccdccdcccccdcd"
        "cccccddcccccccdccccdcccdccccdccdccdcccccdcccccccecbccdcccdccccdccdccccdcccdccccdcccccdccccdccccdcccd"
        "ccccdcccdccccdcccdcccdcccdccccdcccccdccccdcccdccccdccdccdccccdcccdccccdcccdccccdccccdcccdccccdcccdcc"
        "ccdcccdccccdccccdcccdccccdcccdccccdcccdccccdcccdccccdccccdcccdccccdcccdccccdcccdccccdcccdccccdccccdc"
        "ccdccccdcccdccccdcccdccccdccccdcccdccccdcccdccccdcccdccccdcccdccccdccccdcccdccccdcccdccccdcccdccccdc"
        "cccdcccdccccdcccdccccdcccdccccdcccdccccdccccd"),
    ),
    (
        (20,
        "ccccccccccccdddefbhebddgdddeddgbdddeddedfedddbgdddeddfbeddgdfdcdddedddefddcdfddeddeddfbefbgddedfbdef"
        "ddedddgdbdfcfbdedfcfbfdeddedfdeaedfeddedfdcddfedddedddeddfcfddgbddchddcddehbddeddfcdfdedbfcfdbefdded"
        "ddefbdefddedddedfdcfdbgdgbdddfcfdbgbffcfbdefddedddgdbhdeddfedddedddeddfedddedddedddgdddedddedddefdde"
        "dddedddefddedddedddedfdedddedddeddfedddedddeddfedddedddedddgdddedddedddgdddedddedddefddedddedddedfde"
        "dddedddedfdedddedddeddfedddedddedddgdddedddedddgdddedddedddefddedddedddedfdedddedddedfdedddedddeddfe"
        "dddedddeddgdddedddedddefddedddedddedfdedddedd"),
        (5,
        "ccccccccccccdccddbedbccecccdccebcccdccdcddcccbecccdccdbdccecdcccccdcccddccccdccdccdccdbddbeccdcdbcdd"
        "ccdcccecbcdcdbcdcdcdbdcdccdcdcdadcddccdcdccccddcccdcccdccdcdccebcccecccccdebccdccdccdcdcbdcdcbddccdc"
        "ccddbcddccdcccdcdccdcbecebcccdcdcbebddcdbcddccdcccecbecdccddcccdcccdccddcccdcccdcccecccdcccdcccddccd"
        "cccdcccddccdcccdcccdcdcdcccdcccdccddcccdcccdccddcccdcccdcccecccdcccdcccecccdcccdcccddccdcccdcccdcdcd"
        "cccdcccdcdcdcccdcccdccddcccdcccdcccecccdcccdcccecccdcccdcccddccdcccdcccdcdcdcccdcccdcdcdcccdcccdccdd"
        "cccdcccdccecccdcccdcccddccdcccdcccdcdcdcccdcc"),
        (7,
        "ccddcecdddefeddefbhebddgdddeddgbdddeddedfedddbgdddeddfbeddgdfdcdddedddefddcdfddeddeddfbefbgddedfbdef"
        "ddedddgdbdfcfbdedfcfbfdeddedfdeaedfeddedfdcddfedddedddeddfcfddgbddchddcddehbddeddfcdfdedbfcfdbefdded"
        "ddefbdefddedddedfdcfdbgdgbdddfcfdbgbffcfbdefddedddgdbhdeddfedddedddeddfedddedddedddgdddedddedddefdde"
        "dddedddefddedddedddedfdedddedddeddfedddedddeddfedddedddedddgdddedddedddgdddedddedddefddedddedddedfde"
        "dddedddedfdedddedddeddfedddedddedddgdddedddedddgdddedddedddefddedddedddedfdedddedddedfdedddedddeddfe"
        "dddedddeddgdddedddedddefddedddedddedfdedddedd"),
        (3,
        "ccccccccccdddccddbedbccecccdccebcccdccdcddcccbecccdccdbdccecdcccccdcccddccccdccdccdccdbddbeccdcdbcdd"
        "ccdcccecbcdcdbcdcdcdbdcdccdcdcdadcddccdcdccccddcccdcccdccdcdccebcccecccccdebccdccdccdcdcbdcdcbddccdc"
        "ccddbcddccdcccdcdccdcbecebcccdcdcbebddcdbcddccdcccecbecdccddcccdcccdccddcccdcccdcccecccdcccdcccddccd"
        "cccdcccddccdcccdcccdcdcdcccdcccdccddcccdcccdccddcccdcccdcccecccdcccdcccecccdcccdcccddccdcccdcccdcdcd"
        "cccdcccdcdcdcccdcccdccddcccdcccdcccecccdcccdcccecccdcccdcccddccdcccdcccdcdcdcccdcccdcdcdcccdcccdccdd"
        "cccdcccdccecccdcccdcccddccdcccdcccdcdcdcccdcc"),
    ),
    (
        (20,
        "ccccccccccccccddddddeddddeddddeddddeddddedddeddddeddddeddddeddddeddddeddddedddeddddeddddeddddedddded"
        "dddedddeddddeddddeddddeddddeddddedddeddddeddddeddddeddddeddddeddddedddeddddeddddeddddeddddeddddeddde"
        "ddddeddddeddddeddddeddddedddeddddeddddeddddeddddeddddeddddedddeddddeddddeddddeddddeddddedddeddddeddd"
        "deddddeddddeddddedddeddddeddddeddddeddddeddddeddddedddeddddeddddeddddeddddeddddedddeddddeddddedddded"
        "dddeddddedddeddddeddddeddddeddddeddddeddddedddeddddeddddeddddeddddeddddedddeddddeddddeddddeddddedddd"
        "edddeddddeddddeddddeddddeddddedddeddddedddded"),
        (5,
        "ccccccccccccccccccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdc"
        "cccdcccdccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdccccdcccd"
        "ccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdccccdcccdccccdccc"
        "cdccccdccccdccccdcccdccccdccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdccccdcccdccccdccccdccccdc"
        "cccdccccdcccdccccdccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdcccc"
        "dcccdccccdccccdccccdccccdccccdcccdccccdccccdc"),
        (7,
        "ccddcecddddedddeddddeddddeddddeddddeddddedddeddddeddddeddddeddddeddddeddddedddeddddeddddeddddedddded"
        "dddedddeddddeddddeddddeddddeddddedddeddddeddddeddddeddddeddddeddddedddeddddeddddeddddeddddeddddeddde"
        "ddddeddddeddddeddddeddddedddeddddeddddeddddeddddeddddeddddedddeddddeddddeddddeddddeddddedddeddddeddd"
        "deddddeddddeddddedddeddddeddddeddddeddddeddddeddddedddeddddeddddeddddeddddeddddedddeddddeddddedddded"
        "dddeddddedddeddddeddddeddddeddddeddddeddddedddeddddeddddeddddeddddeddddedddeddddeddddeddddeddddedddd"
        "edddeddddeddddeddddeddddeddddedddeddddedddded"),
        (3,
        "cccccccccccdcccdccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdc"
        "cccdcccdccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdccccdcccd"
        "ccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdccccdcccdccccdccc"
        "cdccccdccccdccccdcccdccccdccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdccccdcccdccccdccccdccccdc"
        "cccdccccdcccdccccdccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdccccdcccdccccdccccdccccdccccdcccc"
        "dcccdccccdccccdccccdccccdccccdcccdccccdccccdc"),
    ),
    (
        (20,
        "ccccccccccccccdddedddedddeddddedddedddedddedddedddedddeddfdedddedddedddedddedddedddeddddedddedddeddd"
        "edddgdddedddeddddedddedddedddedddedddedddeddddeddbedfdedddedddedddeddcdedddedddedddedddedddedddedddf"
        "edddedddedddedddedddedddeddddedddedddddddedddefddedddbdeddddedddeddddeddddedddeddddedddeddddefdddedd"
        "deddddeddddedddeddddedddeddddeddddedddedfddeddddedddeddddedddeddddeddddedddeddddeddddedfdeddddeddded"
        "dddeddddedddeddddeddddedddeddddeddfeddddeddddedddeddddedddeddddeddddedddeddddedddfedddeddddedddedddd"
        "eddddedddeddddeddddedddeddddgdddeddddeddddedd"),
        (5,
        "cccccccccccccccccdcccdcccdccccdcccdcccdcccdcccdcccdcccdccdcdcccdcccdcccdcccdcccdcccdccccdcccdcccdccc"
        "dcccecccdcccdccccdcccdcccdcccdcccdcccdcccdccccdccadcdcdcccdcccdcccdccbcdcccdcccdcccdcccdcccdcccdcccd"
        "dcccdcccdcccdcccdcccdcccdccccdcccdcccccccdcccddccdcccacdccccdcccdccccdccccdcccdccccdcccdccccddcccdcc"
        "cdccccdccccdcccdccccdcccdccccdccccdcccdcdccdccccdcccdccccdcccdccccdccccdcccdccccdccccdcdcdccccdcccdc"
        "cccdccccdcccdccccdccccdcccdccccdccddccccdccccdcccdccccdcccdccccdccccdcccdccccdcccddcccdccccdcccdcccc"
        "dccccdcccdccccdccccdcccdccccecccdccccdccccdcc"),
        (7,
        "ccddcecddedddedddedddedddeddddedddedddedddedddedddedddeddfdedddedddedddedddedddedddeddddedddedddeddd"
        "edddgdddedddeddddedddedddedddedddedddedddeddddeddbedfdedddedddedddeddcdedddedddedddedddedddedddedddf"
        "edddedddedddedddedddedddeddddedddedddddddedddefddedddbdeddddedddeddddeddddedddeddddedddeddddefdddedd"
        "deddddeddddedddeddddedddeddddeddddedddedfddeddddedddeddddedddeddddeddddedddeddddeddddedfdeddddeddded"
        "dddeddddedddeddddeddddedddeddddeddfeddddeddddedddeddddedddeddddeddddedddeddddedddfedddeddddedddedddd"
        "eddddedddeddddeddddedddeddddgdddeddddeddddedd"),
        (3,
        "cccccccccdcccdcccdcccdcccdccccdcccdcccdcccdcccdcccdcccdccdcdcccdcccdcccdcccdcccdcccdccccdcccdcccdccc"
        "dcccecccdcccdccccdcccdcccdcccdcccdcccdcccdccccdccadcdcdcccdcccdcccdccbcdcccdcccdcccdcccdcccdcccdcccd"
        "dcccdcccdcccdcccdcccdcccdccccdcccdcccccccdcccddccdcccacdccccdcccdccccdccccdcccdccccdcccdccccddcccdcc"
        "cdccccdccccdcccdccccdcccdccccdccccdcccdcdccdccccdcccdccccdcccdccccdccccdcccdccccdccccdcdcdccccdcccdc"
        "cccdccccdcccdccccdccccdcccdccccdccddccccdccccdcccdccccdcccdccccdccccdcccdccccdcccddcccdccccdcccdcccc"
        "dccccdcccdccccdccccdcccdccccecccdccccdccccdcc"),
    ),
    (
        (20,
        "ccccccccccccccdddeddddddedddeddddedddeddddedddedddedddddefdddedddedddedddddedeceddddeddddedddedddded"
        "dddefddeddeceddecedddeddddeddddedddedddedddedecdedddgcedddeddddeddddeddeddeceddddedddedddddedddedddf"
        "edddeddeceddddedddeddddeddddedddeddddeddecedddgddddedddeddddedddeddddeddddedddeddddedddeddddefdddedd"
        "deddddeddddedddeddddedddeddddeddddedddedfddeddddedddeddddedddeddddeddddedddeddddeddddedfdeddddeddded"
        "dddeddddedddeddddeddddedddeddddeddfeddddeddddedddeddddedddeddddeddddedddeddddedddfedddeddddedddedddd"
        "eddddedddeddddeddddedddeddddgdddeddddeddddedd"),
        (5,
        "cccccccccccccccccdccccccdcccdccccdcccdccccdcccdcccdcccccddcccdcccdcccdcccccdcdbdccccdccccdcccdccccdc"
        "cccddccdccdbdccdbdcccdccccdccccdcccdcccdcccdcdbcdcccebdcccdccccdccccdccdccdbdccccdcccdcccccdcccdcccd"
        "dcccdccdbdccccdcccdccccdccccdcccdccccdccdbdccceccccdcccdccccdcccdccccdccccdcccdccccdcccdccccddcccdcc"
        "cdccccdccccdcccdccccdcccdccccdccccdcccdcdccdccccdcccdccccdcccdccccdccccdcccdccccdccccdcdcdccccdcccdc"
        "cccdccccdcccdccccdccccdcccdccccdccddccccdccccdcccdccccdcccdccccdccccdcccdccccdcccddcccdccccdcccdcccc"
        "dccccdcccdccccdccccdcccdccccecccdccccdccccdcc"),
        (7,
        "ccddcecdddedddeddeddddddedddeddddedddeddddedddedddedddddefdddedddedddedddddedeceddddeddddedddedddded"
        "dddefddeddeceddecedddeddddeddddedddedddedddedecdedddgcedddeddddeddddeddeddeceddddedddedddddedddedddf"
        "edddeddeceddddedddeddddeddddedddeddddeddecedddgddddedddeddddedddeddddeddddedddeddddedddeddddefdddedd"
        "deddddeddddedddeddddedddeddddeddddedddedfddeddddedddeddddedddeddddeddddedddeddddeddddedfdeddddeddded"
        "dddeddddedddeddddeddddedddeddddeddfeddddeddddedddeddddedddeddddeddddedddeddddedddfedddeddddedddedddd"
        "eddddedddeddddeddddedddeddddgdddeddddeddddedd"),
        (3,
        "ccccccccccdcccdccdccccccdcccdccccdcccdccccdcccdcccdcccccddcccdcccdcccdcccccdcdbdccccdccccdcccdccccdc"
        "cccddccdccdbdccdbdcccdccccdccccdcccdcccdcccdcdbcdcccebdcccdccccdccccdccdccdbdccccdcccdcccccdcccdcccd"
        "dcccdccdbdccccdcccdccccdccccdcccdccccdccdbdccceccccdcccdccccdcccdccccdccccdcccdccccdcccdccccddcccdcc"
        "cdccccdccccdcccdccccdcccdccccdccccdcccdcdccdccccdcccdccccdcccdccccdccccdcccdccccdccccdcdcdccccdcccdc"
        "cccdccccdcccdccccdccccdcccdccccdccddccccdccccdcccdccccdcccdccccdccccdcccdccccdcccddcccdccccdcccdcccc"
        "dccccdcccdccccdccccdcccdccccecccdccccdccccdcc"),
    ),
    (
        (20,
        "ccccccccccccccdddedddedddeddddedddedddedddedddedddedddeddfdedddedddedddedddedddedddeddddedddedddeddd"
        "edddgdddedddeddddedddedddedddedddedddedddeddddeddbedfdedddedddedddeddcdedddedddddddddedececedddeeddf"
        "edddedddeddcedddedddedddeddddeddeeddddddcedddefecedddddeddddedddeddddeddddedddeddddedddeddddefdddedd"
        "deddddeddddedddeddddedddeddddeddddedddedfddeddddedddeddddedddeddddeddddedddeddddeddddedfdeddddeddded"
        "dddeddddedddeddddeddddedddeddddeddfeddddeddddedddeddddedddeddddeddddedddeddddedddfedddeddddedddedddd"
        "eddddedddeddddeddddedddeddddgdddeddddeddddedd"),
        (5,
        "cccccccccccccccccdcccdcccdccccdcccdcccdcccdcccdcccdcccdccdcdcccdcccdcccdcccdcccdcccdccccdcccdcccdccc"
        "dcccecccdcccdccccdcccdcccdcccdcccdcccdcccdccccdccadcdcdcccdcccdcccdccbcdcccdcccccccccdcdbdbdcccddccd"
        "dcccdcccdccbdcccdcccdcccdccccdccddccccccbdcccdddbdcccccdccccdcccdccccdccccdcccdccccdcccdccccddcccdcc"
        "cdccccdccccdcccdccccdcccdccccdccccdcccdcdccdccccdcccdccccdcccdccccdccccdcccdccccdccccdcdcdccccdcccdc"
        "cccdccccdcccdccccdccccdcccdccccdccddccccdccccdcccdccccdcccdccccdccccdcccdccccdcccddcccdccccdcccdcccc"
        "dccccdcccdccccdccccdcccdccccecccdccccdccccdcc"),
        (7,
        "ccddcecddedddedddedddedddeddddedddedddedddedddedddedddeddfdedddedddedddedddedddedddeddddedddedddeddd"
        "edddgdddedddeddddedddedddedddedddedddedddeddddeddbedfdedddedddedddeddcdedddedddddddddedececedddeeddf"
        "edddedddeddcedddedddedddeddddeddeeddddddcedddefecedddddeddddedddeddddeddddedddeddddedddeddddefdddedd"
        "deddddeddddedddeddddedddeddddeddddedddedfddeddddedddeddddedddeddddeddddedddeddddeddddedfdeddddeddded"
        "dddeddddedddeddddeddddedddeddddeddfeddddeddddedddeddddedddeddddeddddedddeddddedddfedddeddddedddedddd"
        "eddddedddeddddeddddedddeddddgdddeddddeddddedd"),
        (3,
        "cccccccccdcccdcccdcccdcccdccccdcccdcccdcccdcccdcccdcccdccdcdcccdcccdcccdcccdcccdcccdccccdcccdcccdccc"
        "dcccecccdcccdccccdcccdcccdcccdcccdcccdcccdccccdccadcdcdcccdcccdcccdccbcdcccdcccccccccdcdbdbdcccddccd"
        "dcccdcccdccbdcccdcccdcccdccccdccddccccccbdcccdddbdcccccdccccdcccdccccdccccdcccdccccdcccdccccddcccdcc"
        "cdccccdccccdcccdccccdcccdccccdccccdcccdcdccdccccdcccdccccdcccdccccdccccdcccdccccdccccdcdcdccccdcccdc"
        "cccdccccdcccdccccdccccdcccdccccdccddccccdccccdcccdccccdcccdccccdccccdcccdccccdcccddcccdccccdcccdcccc"
        "dccccdcccdccccdccccdcccdccccecccdccccdccccdcc"),
    ),
    (
        (20,
        "ccccccccccccccdededcdedddddddedddeddddedddedddeddddedddedfdddeddddedddeddddeddddeddeddedcedddedddded"
        "dddefddeddedddddeddddeddddeddddedddeddddedddeddddeddfdedddeddddedddedddeddddeddddeddddeddddedddedddg"
        "dddddedddeddddedddedddedddddedddeddddeddddededfddddedddeddddedddeddddeddddedddeddddedddeddddefdddedd"
        "deddddeddddedddeddddedddeddddeddddedddedfddeddddedddeddddedddeddddeddddedddeddddeddddedfdeddddeddded"
        "dddeddddedddeddddeddddedddeddddeddfeddddeddddedddeddddedddeddddeddddedddeddddedddfedddeddddedddedddd"
        "eddddedddeddddeddddedddeddddgdddeddddeddddedd"),
        (5,
        "cccccccccccccccdcdcbcdcccccccdcccdccccdcccdcccdccccdcccdcdcccdccccdcccdccccdccccdccdccdcbdcccdccccdc"
        "cccddccdccdcccccdccccdccccdccccdcccdccccdcccdccccdccdcdcccdccccdcccdcccdccccdccccdccccdccccdcccdccce"
        "cccccdcccdccccdcccdcccdcccccdcccdccccdccccdcdcdccccdcccdccccdcccdccccdccccdcccdccccdcccdccccddcccdcc"
        "cdccccdccccdcccdccccdcccdccccdccccdcccdcdccdccccdcccdccccdcccdccccdccccdcccdccccdccccdcdcdccccdcccdc"
        "cccdccccdcccdccccdccccdcccdccccdccddccccdccccdcccdccccdcccdccccdccccdcccdccccdcccddcccdccccdcccdcccc"
        "dccccdcccdccccdccccdcccdccccecccdccccdccccdcc"),
        (7,
        "ccddcecddededddededcdedddddddedddeddddedddedddeddddedddedfdddeddddedddeddddeddddeddeddedcedddedddded"
        "dddefddeddedddddeddddeddddeddddedddeddddedddeddddeddfdedddeddddedddedddeddddeddddeddddeddddedddedddg"
        "dddddedddeddddedddedddedddddedddeddddeddddededfddddedddeddddedddeddddeddddedddeddddedddeddddefdddedd"
        "deddddeddddedddeddddedddeddddeddddedddedfddeddddedddeddddedddeddddeddddedddeddddeddddedfdeddddeddded"
        "dddeddddedddeddddeddddedddeddddeddfeddddeddddedddeddddedddeddddeddddedddeddddedddfedddeddddedddedddd"
        "eddddedddeddddeddddedddeddddgdddeddddeddddedd"),
        (3,
        "cccccccccdcdcccdcdcbcdcccccccdcccdccccdcccdcccdccccdcccdcdcccdccccdcccdccccdccccdccdccdcbdcccdccccdc"
        "cccddccdccdcccccdccccdccccdccccdcccdccccdcccdccccdccdcdcccdccccdcccdcccdccccdccccdccccdccccdcccdccce"
        "cccccdcccdccccdcccdcccdcccccdcccdccccdccccdcdcdccccdcccdccccdcccdccccdccccdcccdccccdcccdccccddcccdcc"
        "cdccccdccccdcccdccccdcccdccccdccccdcccdcdccdccccdcccdccccdcccdccccdccccdcccdccccdccccdcdcdccccdcccdc"
        "cccdccccdcccdccccdccccdcccdccccdccddccccdccccdcccdccccdcccdccccdccccdcccdccccdcccddcccdccccdcccdcccc"
        "dccccdcccdccccdccccdcccdccccecccdccccdccccdcc"),
    ),
    (
        (20,
        "ccccccccccccccddddfbdedfdbeddfbeddfdcdddfcdddfebdddgbdddgddbdefbddefdbdedfdbedfdcdddfebddffbdddgbddd"
        "gdbddefbddefbddedfbdedfbdedfdbeddfbeddfdcdddfcdddfebfbdgbfbdgdbfbefbfbefddbedfddcdfddcddfdebdfdcdddf"
        "edbdfebdddgbfbdgddbdefbfbefddbedfbdedfddcddfdcddfeddbhddddeddddeddddedddeddddefdddeddddedddeddddeddd"
        "deddddedddeddddeddddeddddeddddedddeddddeddddeddddedddeddddeddddeddddedddeddddeddddeddddedddeddddeddd"
        "deddddedddeddddeddddeddddeddddedddeddddeddddeddddedddeddddeddddefdddedddeddddeddddeddddedddeddddeddd"
        "deddddedddeddddeddddeddddeddddedddeddddedddde"),
        (5,
        "ccccccccccccccccccdbcdcdcbdccdbdccdcccccdccccddbcccebccceccbcddbccddcbcdcdcbdcdcccccddbccdebcccebccc"
        "ecbccddbccddbccdcdbcdcdbcdcdcbdccdbdccdcccccdccccddbdbcebdbcecbdbddbdbddccbdcdccccdcccccdcdbcdcccccd"
        "dcbcddbcccebdbceccbcddbdbddccbdcdbcdcdcccccdccccddccbfccccdccccdccccdcccdccccddcccdccccdcccdccccdccc"
        "cdccccdcccdccccdccccdccccdccccdcccdccccdccccdccccdcccdccccdccccdccccdcccdccccdccccdccccdcccdccccdccc"
        "cdccccdcccdccccdccccdccccdccccdcccdccccdccccdccccdcccdccccdccccddcccdcccdccccdccccdccccdcccdccccdccc"
        "cdccccdcccdccccdccccdccccdccccdcccdccccdccccd"),
        (7,
        "ccddcecddddeddddedfbdedfdbeddfbeddfdcdddfcdddfebdddgbdddgddbdefbddefdbdedfdbedfdcdddfebddffbdddgbddd"
        "gdbddefbddefbddedfbdedfbdedfdbeddfbeddfdcdddfcdddfebfbdgbfbdgdbfbefbfbefddbedfddcdfddcddfdebdfdcdddf"
        "edbdfebdddgbfbdgddbdefbfbefddbedfbdedfddcddfdcddfeddbhddddeddddeddddedddeddddefdddeddddedddeddddeddd"
        "deddddedddeddddeddddeddddeddddedddeddddeddddeddddedddeddddeddddeddddedddeddddeddddeddddedddeddddeddd"
        "deddddedddeddddeddddeddddeddddedddeddddeddddeddddedddeddddeddddefdddedddeddddeddddeddddedddeddddeddd"
        "deddddedddeddddeddddeddddeddddedddeddddedddde"),
        (3,
        "cccccccccccdccccdcdbcdcdcbdccdbdccdcccccdccccddbcccebccceccbcddbccddcbcdcdcbdcdcccccddbccdebcccebccc"
        "ecbccddbccddbccdcdbcdcdbcdcdcbdccdbdccdcccccdccccddbdbcebdbcecbdbddbdbddccbdcdccccdcccccdcdbcdcccccd"
        "dcbcddbcccebdbceccbcddbdbddccbdcdbcdcdcccccdccccddccbfccccdccccdccccdcccdccccddcccdccccdcccdccccdccc"
        "cdccccdcccdccccdccccdccccdccccdcccdccccdccccdccccdcccdccccdccccdccccdcccdccccdccccdccccdcccdccccdccc"
        "cdccccdcccdccccdccccdccccdccccdcccdccccdccccdccccdcccdccccdccccddcccdcccdccccdccccdccccdcccdccccdccc"
        "cdccccdcccdccccdccccdccccdccccdcccdccccdccccd"),
    ),
)
#: (font, bold, italic) -> the table measured for it.
_OWNER: dict[tuple[str, bool, bool], int] = {
    ('aptos', False, False): 0,
    ('aptos', False, True): 0,
    ('aptos', True, False): 0,
    ('aptos', True, True): 0,
    ('aptos display', False, False): 0,
    ('aptos display', False, True): 0,
    ('aptos display', True, False): 0,
    ('aptos display', True, True): 0,
    ('aptos narrow', False, False): 0,
    ('aptos narrow', False, True): 0,
    ('aptos narrow', True, False): 0,
    ('aptos narrow', True, True): 0,
    ('arial', False, False): 1,
    ('arial', False, True): 3,
    ('arial', True, False): 2,
    ('arial', True, True): 4,
    ('calibri', False, False): 5,
    ('calibri', False, True): 5,
    ('calibri', True, False): 5,
    ('calibri', True, True): 5,
    ('calibri light', False, False): 5,
    ('calibri light', False, True): 5,
    ('calibri light', True, False): 5,
    ('calibri light', True, True): 5,
    ('cambria', False, False): 6,
    ('cambria', False, True): 6,
    ('cambria', True, False): 6,
    ('cambria', True, True): 6,
    ('consolas', False, False): 7,
    ('consolas', False, True): 7,
    ('consolas', True, False): 7,
    ('consolas', True, True): 7,
    ('courier new', False, False): 8,
    ('courier new', False, True): 10,
    ('courier new', True, False): 9,
    ('courier new', True, True): 9,
    ('georgia', False, False): 11,
    ('georgia', False, True): 11,
    ('georgia', True, False): 11,
    ('georgia', True, True): 11,
    ('segoe ui', False, False): 12,
    ('segoe ui', False, True): 12,
    ('segoe ui', True, False): 12,
    ('segoe ui', True, True): 12,
    ('tahoma', False, False): 13,
    ('tahoma', False, True): 13,
    ('tahoma', True, False): 13,
    ('tahoma', True, True): 13,
    ('times new roman', False, False): 14,
    ('times new roman', False, True): 16,
    ('times new roman', True, False): 15,
    ('times new roman', True, True): 17,
    ('verdana', False, False): 18,
    ('verdana', False, True): 18,
    ('verdana', True, False): 18,
    ('verdana', True, True): 18,
}


@cache
def _decoded(index: int) -> tuple[tuple[int, ...], ...]:
    return tuple(_run(first, steps) for first, steps in _TABLES[index])


def _run(first: int, steps: str) -> tuple[int, ...]:
    values = [first]
    for step in steps:
        values.append(values[-1] + _ALPHABET.index(step) + _LOWEST)
    return tuple(values)


def table_of(font: str, bold: bool, italic: bool) -> int | None:
    """Which measured table a font and style use, or None when it was not measured."""
    return _OWNER.get((font.lower(), bold, italic))


def row_of(table: int, pixels: int, *, alone: bool = False) -> tuple[int, int]:
    """The row's height in pixels and its descent in twips, at a pixel size from 1 to MOST_PIXELS.

    Beside the Normal font unless alone, when no position in the row
    shows the Normal font.
    """
    rows, descents, alone_rows, alone_descents = _decoded(table)
    if alone:
        return alone_rows[pixels - 1], alone_descents[pixels - 1]
    return rows[pixels - 1], descents[pixels - 1]
