"""RE analyzer for the project-wide VBA LVAL chain in .accdb files.

Each .accdb that contains a VBA project stores its entire project state
in a single chained LVAL long-value. The chain payload is structured as:

  1. A plaintext PROJECT file (same line-based format Excel/Word ship in
     their CFB PROJECT stream): ``ID=...\\r\\nModule=...\\r\\n...\\r\\nZ\\r\\n``.
  2. A binary catalog / symbol-table block (undocumented; subject of this
     reverse-engineering effort).
  3. One MS-OVBA-compressed stream per VBA module: ``Attribute VB_Name =
     "<name>"\\r\\nOption Compare Database\\r\\n<body>\\r\\n``.
  4. Plaintext source-row tables (``B9`` rows for string-literal text,
     ``E3`` rows for comment text -- the authoritative store Access reads).

This module locates the chain in any .accdb, walks every linked LVAL
page, reassembles the payload into a contiguous byte stream, and emits
section boundaries plus per-section hex/ASCII dumps suitable for diffing
across the corpus generated by ``_corpus_generate.ps1``.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from dataclasses import dataclass

PAGE = 4096
LVAL_HEADER_LEN = 28


@dataclass
class ChainInfo:
    head_page: int
    pages: list[int]
    head_payload_offset_in_page: int  # byte offset within head page where payload starts
    payload: bytes                     # reassembled cross-page payload


def is_lval_page(data: bytes, page_num: int) -> bool:
    base = page_num * PAGE
    return data[base] == 0x01 and data[base + 4 : base + 8] == b"LVAL"


PROJECT_FINGERPRINT = b'ID="{'


def find_project_chain(data: bytes) -> ChainInfo | None:
    """Locate the head LVAL page of the project-wide VBA record by
    searching every LVAL page for the ``ID="{...}"`` plaintext
    fingerprint that opens the PROJECT file. Returns ``None`` if the
    .accdb has no VBA project.

    Multi-page chunk reassembly is not yet implemented (see module
    docstring), so ``payload`` is the head-page slice only."""
    n_pages = len(data) // PAGE
    for p in range(n_pages):
        if not is_lval_page(data, p):
            continue
        base = p * PAGE
        body = data[base + LVAL_HEADER_LEN : base + PAGE]
        j = body.find(PROJECT_FINGERPRINT)
        if j < 0:
            continue
        head_payload_offset_in_page = LVAL_HEADER_LEN + j
        payload = bytes(data[base + head_payload_offset_in_page : base + PAGE])
        return ChainInfo(
            head_page=p,
            pages=[p],
            head_payload_offset_in_page=head_payload_offset_in_page,
            payload=payload,
        )
    return None


def split_sections(payload: bytes) -> dict[str, tuple[int, int]]:
    """Identify the well-known section boundaries inside the chain
    payload. Returns ``{name: (start, end)}`` (end-exclusive). Unknown
    intervals fall in a synthesized ``binary`` section between known
    plaintext sections."""
    out: dict[str, tuple[int, int]] = {}
    # Section 1: plaintext PROJECT file from "ID=" to the trailing "Z\r\n".
    proj_start = payload.find(b'ID="{')
    if proj_start < 0:
        return out
    # The PROJECT file is terminated by a line starting with "Z" and a CRLF
    # (the workspace section's final line). Find the last occurrence.
    z_line = payload.find(b", Z\r\n", proj_start)
    if z_line >= 0:
        proj_end = z_line + len(b", Z\r\n")
    else:
        # Fallback: empty workspace -- find first NUL after proj_start.
        nul = payload.find(b"\x00", proj_start)
        proj_end = nul if nul > 0 else proj_start
    out["project_plaintext"] = (proj_start, proj_end)

    # Section 2: OVBA stream(s). Each begins with byte 0x01 followed by
    # a 2-byte little-endian header whose top nibble is 0xB. We list the
    # first such position after the PROJECT section.
    p = proj_end
    while p < len(payload) - 2:
        if payload[p] == 0x01 and (payload[p + 2] & 0xF0) == 0xB0:
            out["ovba_first"] = (p, p)  # length not yet known
            break
        p += 1

    # Section 3: B9 string-literal rows. Scan for the marker.
    b9 = payload.find(b"\xb9\x00", proj_end)
    if b9 >= 0:
        out["b9_row_first"] = (b9, b9)

    # Section 4: E3 comment rows.
    e3 = payload.find(b"\xe3\x00\x00\x00", proj_end)
    if e3 >= 0:
        out["e3_row_first"] = (e3, e3)

    return out


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("accdb", type=Path)
    parser.add_argument("--dump", type=Path, default=None,
                        help="write the full chain payload to this file")
    parser.add_argument("--summary-only", action="store_true")
    args = parser.parse_args()

    data = args.accdb.read_bytes()
    chain = find_project_chain(data)
    if chain is None:
        print(f"{args.accdb.name}: no VBA project chain found")
        sys.exit(1)

    print(f"== {args.accdb.name} ==")
    print(f"  file: {len(data):,} bytes ({len(data)//PAGE} pages)")
    print(f"  chain head page: {chain.head_page}")
    print(f"  chain length:    {len(chain.pages)} pages -> {chain.pages}")
    print(f"  payload size:    {len(chain.payload):,} bytes")
    sections = split_sections(chain.payload)
    for name, (s, e) in sections.items():
        print(f"  section {name:24s} @ payload[0x{s:06X}..0x{e:06X}]  ({e - s} bytes)")

    if args.dump is not None:
        args.dump.write_bytes(chain.payload)
        print(f"  wrote payload -> {args.dump}")


if __name__ == "__main__":
    main()
