"""Bake the blank Access database into ``pyopenvba._templates``.

Mirrors the other hosts: the canonical blank file in
``_templates/blank_files/`` is zlib-compressed, base85-encoded and
appended to ``_templates/__init__.py`` as ``EMPTY_ACCDB_BYTES``.

An ``.accdb`` is mostly empty pages, so it compresses to about 4% of its
size -- a 290 KB database becomes roughly 15 KB of source text, in line
with the Office templates already embedded there.

    python docs/research/access_write/bake_access_template.py
"""
from __future__ import annotations

import base64
import textwrap
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
BLANK = (ROOT / "src" / "pyopenvba" / "_templates" / "blank_files"
         / "blank_database_module.accdb")
TARGET = ROOT / "src" / "pyopenvba" / "_templates" / "__init__.py"


def main() -> int:
    raw = BLANK.read_bytes()
    packed = zlib.compress(raw, 9)
    encoded = base64.b85encode(packed).decode("ascii")
    body = "\n".join(f'    "{chunk}"'
                     for chunk in textwrap.wrap(encoded, 76))
    block = (
        f"\n\n# --- ACCDB template (generated by bake_access_template.py) ---\n"
        f"# Source bytes: {len(raw)} | zlib: {len(packed)} | "
        f"base85: {len(encoded)}\n"
        f"_EMPTY_ACCDB_B85 = (\n{body}\n)\n\n"
        f"EMPTY_ACCDB_BYTES: bytes = zlib.decompress("
        f"base64.b85decode(_EMPTY_ACCDB_B85))\n"
    )
    text = TARGET.read_text()
    if "_EMPTY_ACCDB_B85" in text:
        head = text.split("\n\n# --- ACCDB template")[0]
        text = head
    TARGET.write_text(text.rstrip("\n") + block)
    print(f"baked {len(raw):,} bytes -> {len(encoded):,} chars of base85")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
