"""Bake the empty .xlsm template into a Python module.

Reads the canonical reference workbook `tests/live_excel_testing/freshly_touched.xlsm`
(a freshly Excel-authored .xlsm containing ThisWorkbook + Sheet1 + Module1),
strips any user-typed content from Module1 so the source is just the bare
`Attribute VB_Name = "Module1"` header, then zlib-compresses + base85-encodes
the resulting bytes and writes them as a constant inside
`src/pyopenvba/_templates/__init__.py`.

The .xlsm file itself is NOT shipped in the wheel; only the generated
Python module is.
"""

from __future__ import annotations

import base64
import textwrap
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REF_XLSM = ROOT / "tests" / "live_excel_testing" / "freshly_touched.xlsm"
OUT_PY = ROOT / "src" / "pyopenvba" / "_templates" / "__init__.py"


def _strip_module1(xlsm_bytes: bytes) -> bytes:
    """Open the workbook, blank Module1's source, return the new .xlsm bytes."""
    from pyopenvba.excel import ExcelFile

    scratch_in = ROOT / "src" / "pyopenvba" / "_templates" / "_scratch_in.xlsm"
    scratch_out = ROOT / "src" / "pyopenvba" / "_templates" / "_scratch_out.xlsm"
    scratch_in.write_bytes(xlsm_bytes)
    try:
        wb = ExcelFile(scratch_in)
        proj = wb.vba_project()
        try:
            m = proj.get_module("Module1")
        except KeyError:
            pass
        else:
            m.source = 'Attribute VB_Name = "Module1"\r\n'
            m.dirty = True
        wb.save(scratch_out)
        return scratch_out.read_bytes()
    finally:
        scratch_in.unlink(missing_ok=True)
        scratch_out.unlink(missing_ok=True)


def main() -> None:
    raw_input = REF_XLSM.read_bytes()
    raw = _strip_module1(raw_input)
    comp = zlib.compress(raw, 9)
    b85 = base64.b85encode(comp).decode("ascii")
    wrapped = textwrap.fill(b85, width=72)
    quoted_lines = "\n".join('    "' + ln + '"' for ln in wrapped.split("\n"))

    header = (
        '"""Embedded empty .xlsm workbook template.\n'
        "\n"
        "Captured from a freshly Excel-authored .xlsm file containing\n"
        "ThisWorkbook + Sheet1 + an empty Module1 document module.\n"
        "Stored here as a zlib-compressed base85 blob so the wheel ships\n"
        "no binary fixtures; decoded on demand by ExcelFile.create_new().\n"
        "\n"
        "This file is generated by `scripts/bake_empty_template.py`.\n"
        "Do not edit by hand.\n"
        '"""\n'
        "\n"
        "from __future__ import annotations\n"
        "\n"
        "import base64\n"
        "import zlib\n"
        "\n"
        f"# Source bytes: {len(raw)} | zlib: {len(comp)} | base85: {len(b85)}\n"
        "_EMPTY_XLSM_B85 = (\n"
    )
    footer = (
        "\n)\n"
        "\n"
        "EMPTY_XLSM_BYTES: bytes = zlib.decompress(base64.b85decode(_EMPTY_XLSM_B85))\n"
    )

    OUT_PY.write_text(header + quoted_lines + footer, encoding="utf-8", newline="\n")
    print(f"wrote {OUT_PY} ({len(raw)} -> {len(comp)} zlib -> {len(b85)} base85)")


if __name__ == "__main__":
    main()
