"""Bake the empty .xlsm template into the shared templates module.

Reads `src/pyopenvba/_templates/blank_files/blank_workbook.xlsm`
(a freshly Excel-authored .xlsm containing only an empty Module1),
zlib-compresses + base85-encodes the bytes and splices the result into
`src/pyopenvba/_templates/__init__.py` as the XLSM section, as the other
bake scripts splice theirs.  The module's header is written only when
the file does not exist yet: the other sections, the XLSX one with no
bake script of its own among them, are kept as they are.

The .xlsm file itself is NOT shipped in the wheel; only the generated blob.

Run from the repo root:
    python scripts/bake_excel_template.py
"""

from __future__ import annotations

import base64
import sys
import textwrap
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REF_XLSM = ROOT / "src" / "pyopenvba" / "_templates" / "blank_files" / "blank_workbook.xlsm"
OUT_PY = ROOT / "src" / "pyopenvba" / "_templates" / "__init__.py"

sys.path.insert(0, str(ROOT / "src"))


def _strip_module1(xlsm_bytes: bytes) -> bytes:
    """Open the workbook, blank Module1's source, return the new .xlsm bytes."""
    from pyopenvba.excel import ExcelFile

    scratch_in  = ROOT / "src" / "pyopenvba" / "_templates" / "_scratch_in.xlsm"
    scratch_out = ROOT / "src" / "pyopenvba" / "_templates" / "_scratch_out.xlsm"
    scratch_in.write_bytes(xlsm_bytes)
    try:
        wb = ExcelFile(scratch_in)
        proj = wb.vba_project()
        try:
            m = proj.get_module("Module1")
        except KeyError:
            pass
        else:
            m.source = 'Attribute VB_Name = "Module1"\r\n'
            m.dirty = True
        wb.save(scratch_out)
        return scratch_out.read_bytes()
    finally:
        scratch_in.unlink(missing_ok=True)
        scratch_out.unlink(missing_ok=True)


_SECTION_START = "# --- XLSM template (generated by bake_excel_template.py) ---"
_SECTION_END = "# --- end XLSM template ---"
#: The module's opening, for when the file does not exist yet.
_HEADER = (
    '"""Embedded empty Office file templates.\n'
    "\n"
    "Each blob is a zlib-compressed base85-encoded Office file containing\n"
    "only an empty Module1, baked from the canonical blank files stored in\n"
    "`src/pyopenvba/_templates/blank_files/`.  Decoded on demand by each\n"
    "host file class's `create_new()` method.\n"
    "\n"
    "This file is generated by the bake_*_template.py scripts.\n"
    "Do not edit by hand.\n"
    '"""\n'
    "\n"
    "from __future__ import annotations\n"
    "\n"
    "import base64\n"
    "import zlib\n"
    "\n"
)


def _build_xlsm_section(raw: bytes, comp: bytes, b85: str) -> str:
    wrapped = textwrap.fill(b85, width=72)
    quoted_lines = "\n".join('    "' + ln + '"' for ln in wrapped.split("\n"))
    return (
        f"{_SECTION_START}\n"
        f"# Source bytes: {len(raw)} | zlib: {len(comp)} | base85: {len(b85)}\n"
        "_EMPTY_XLSM_B85 = (\n"
        f"{quoted_lines}\n"
        ")\n"
        "\n"
        "EMPTY_XLSM_BYTES: bytes = zlib.decompress(base64.b85decode(_EMPTY_XLSM_B85))\n"
        f"{_SECTION_END}\n"
    )


def _splice(existing: str, new_section: str) -> str:
    """Replace the XLSM section, or put one after the module's header if there is none."""
    if _SECTION_START in existing:
        start = existing.index(_SECTION_START)
        end = existing.index(_SECTION_END) + len(_SECTION_END)
        if end < len(existing) and existing[end] == "\n":
            end += 1
        return existing[:start] + new_section + existing[end:]
    return existing.rstrip("\n") + "\n\n" + new_section


def main() -> None:
    raw_input = REF_XLSM.read_bytes()
    raw = _strip_module1(raw_input)
    comp = zlib.compress(raw, 9)
    b85 = base64.b85encode(comp).decode("ascii")

    section = _build_xlsm_section(raw, comp, b85)
    existing = OUT_PY.read_text(encoding="utf-8") if OUT_PY.exists() else _HEADER
    OUT_PY.write_text(_splice(existing, section), encoding="utf-8", newline="\n")
    print(f"wrote {OUT_PY}  ({len(raw)} -> {len(comp)} zlib -> {len(b85)} base85)")


if __name__ == "__main__":
    main()
