"""Bake tests/fixtures/font_rows.json into src/pyopenvba/apps/excel/_font_rows.py.

The fixture is what scripts/measure_font_heights.py measured in live Excel:
for each font and style, at every pixel size from 1 to 546, the height in
pixels Excel gives a row and the descent it writes for it, in twips, both
with the Normal font elsewhere in the row and with the font alone there.
Styles and fonts whose measurements are identical share one table, and
each sequence is kept as its first value and one letter per step from
each pixel size to the next.

    python scripts/bake_font_rows.py
"""

from __future__ import annotations

import json
import textwrap
from itertools import pairwise
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIXTURE = ROOT / "tests" / "fixtures" / "font_rows.json"
MODULE = ROOT / "src" / "pyopenvba" / "apps" / "excel" / "_font_rows.py"
#: One letter per step; "a" is the smallest step any table takes.
ALPHABET = "abcdefghijklmnopqrstuvwxyz"


def encoded(values: list[int], lowest: int) -> str:
    return "".join(ALPHABET[b - a - lowest] for a, b in pairwise(values))


#: The sequences each table holds, in the order the module keeps them.
SEQUENCES = ("rows", "descent", "alone", "alone_descent")


def main() -> None:
    tables = json.loads(FIXTURE.read_text(encoding="utf-8"))
    steps = [b - a for table in tables for key in SEQUENCES for a, b in pairwise(table[key])]
    lowest = min(steps)
    assert max(steps) - lowest < len(ALPHABET), "steps too wide for one letter each"
    distinct: dict[tuple[tuple[int, ...], ...], int] = {}
    owner: dict[tuple[str, bool, bool], int] = {}
    for table in tables:
        key = tuple(tuple(table[name]) for name in SEQUENCES)
        index = distinct.setdefault(key, len(distinct))
        owner[(table["font"].lower(), table["bold"], table["italic"])] = index
    fonts = sorted({font for font, _, _ in owner})
    # A font measured in regular only shares every style's table with it: the
    # measurement confirmed as much for Aptos Display, Aptos Narrow and Calibri Light.
    for font in fonts:
        base = owner[(font, False, False)]
        for bold in (False, True):
            for italic in (False, True):
                owner.setdefault((font, bold, italic), base)
    entries: list[str] = []
    for sequences, _ in sorted(distinct.items(), key=lambda item: item[1]):
        parts: list[str] = []
        for values in sequences:
            steps_text = textwrap.indent("\n".join(f'"{line}"' for line in textwrap.wrap(
                encoded(list(values), lowest), 100)), " " * 8)
            parts.append(f"        ({values[0]},\n{steps_text}),")
        entries.append("    (\n" + "\n".join(parts) + "\n    ),")
    owners = "\n".join(f"    ({font!r}, {bold}, {italic}): {index},"
                       for (font, bold, italic), index in sorted(owner.items()))
    text = f'''"""How tall a font makes a row, as Excel measures it on a 96-DPI display.

Generated by scripts/bake_font_rows.py from tests/fixtures/font_rows.json,
which scripts/measure_font_heights.py measured in live Excel. For each font
and style, at every pixel size from 1 to {len(tables[0]["rows"])} (409.5pt), the table holds
the height in pixels of a row whose only font besides the Normal one it
is, and the descent Excel writes for that row, in twips; then the same
for a row the font has to itself, which a small font leaves shorter than
the standard row. The heights follow each font's hinted metrics
irregularly enough that no formula over the font's own tables reproduces
them. Do not edit by hand.
"""

from __future__ import annotations

from functools import cache

MOST_PIXELS = {len(tables[0]["rows"])}
#: One letter per step from one pixel size to the next; "a" is {lowest}.
_ALPHABET = "{ALPHABET}"
_LOWEST = {lowest}
#: Each table: the row heights and descents beside the Normal font, then
#: the row heights and descents alone, each as its first value and steps.
_TABLES: tuple[tuple[tuple[int, str], ...], ...] = (
{chr(10).join(entries)}
)
#: (font, bold, italic) -> the table measured for it.
_OWNER: dict[tuple[str, bool, bool], int] = {{
{owners}
}}


@cache
def _decoded(index: int) -> tuple[tuple[int, ...], ...]:
    return tuple(_run(first, steps) for first, steps in _TABLES[index])


def _run(first: int, steps: str) -> tuple[int, ...]:
    values = [first]
    for step in steps:
        values.append(values[-1] + _ALPHABET.index(step) + _LOWEST)
    return tuple(values)


def table_of(font: str, bold: bool, italic: bool) -> int | None:
    """Which measured table a font and style use, or None when it was not measured."""
    return _OWNER.get((font.lower(), bold, italic))


def row_of(table: int, pixels: int, *, alone: bool = False) -> tuple[int, int]:
    """The row's height in pixels and its descent in twips, at a pixel size from 1 to MOST_PIXELS.

    Beside the Normal font unless alone, when no position in the row
    shows the Normal font.
    """
    rows, descents, alone_rows, alone_descents = _decoded(table)
    if alone:
        return alone_rows[pixels - 1], alone_descents[pixels - 1]
    return rows[pixels - 1], descents[pixels - 1]
'''
    MODULE.write_text(text, encoding="utf-8")
    print("wrote", MODULE, len(distinct), "tables for", len(owner), "fonts and styles")


if __name__ == "__main__":
    main()
