"""Bake the empty .pptm template into the shared templates module.

Reads `src/pyopenvba/_templates/blank_files/blank_presentation.pptm`
(a freshly PowerPoint-authored .pptm containing only an empty Module1),
zlib-compresses + base85-encodes the result and splices it into
`src/pyopenvba/_templates/__init__.py` as ``_EMPTY_PPTM_B85`` /
``EMPTY_PPTM_BYTES``.

The .pptm file itself is NOT shipped in the wheel; only the generated blob.

Run from the repo root:
    python scripts/bake_powerpoint_template.py
"""

from __future__ import annotations

import base64
import sys
import textwrap
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REF_PPTM = ROOT / "src" / "pyopenvba" / "_templates" / "blank_files" / "blank_presentation.pptm"
OUT_PY = ROOT / "src" / "pyopenvba" / "_templates" / "__init__.py"

sys.path.insert(0, str(ROOT / "src"))


def _strip_module1(pptm_bytes: bytes) -> bytes:
    """Open the presentation, blank Module1's source, return new .pptm bytes."""
    from pyopenvba.powerpoint import PowerPointFile

    scratch_in  = ROOT / "src" / "pyopenvba" / "_templates" / "_scratch_in.pptm"
    scratch_out = ROOT / "src" / "pyopenvba" / "_templates" / "_scratch_out.pptm"
    scratch_in.write_bytes(pptm_bytes)
    try:
        prs = PowerPointFile(scratch_in)
        proj = prs.vba_project()
        try:
            m = proj.get_module("Module1")
        except KeyError:
            pass
        else:
            m.source = 'Attribute VB_Name = "Module1"\r\n'
            m.dirty = True
        prs.save(scratch_out)
        return scratch_out.read_bytes()
    finally:
        scratch_in.unlink(missing_ok=True)
        scratch_out.unlink(missing_ok=True)


_SECTION_START = "# --- PPTM template (generated by bake_powerpoint_template.py) ---"
_SECTION_END   = "# --- end PPTM template ---"


def _build_pptm_section(raw: bytes, comp: bytes, b85: str) -> str:
    wrapped = textwrap.fill(b85, width=72)
    quoted_lines = "\n".join('    "' + ln + '"' for ln in wrapped.split("\n"))
    return (
        f"{_SECTION_START}\n"
        f"# Source bytes: {len(raw)} | zlib: {len(comp)} | base85: {len(b85)}\n"
        "_EMPTY_PPTM_B85 = (\n"
        f"{quoted_lines}\n"
        ")\n"
        "\n"
        "EMPTY_PPTM_BYTES: bytes = zlib.decompress(base64.b85decode(_EMPTY_PPTM_B85))\n"
        f"{_SECTION_END}\n"
    )


def _splice(existing: str, new_section: str) -> str:
    """Replace an existing PPTM section or append one if absent."""
    if _SECTION_START in existing:
        start = existing.index(_SECTION_START)
        end   = existing.index(_SECTION_END) + len(_SECTION_END)
        if end < len(existing) and existing[end] == "\n":
            end += 1
        return existing[:start] + new_section + existing[end:]
    return existing.rstrip("\n") + "\n\n" + new_section


def main() -> None:
    if not REF_PPTM.exists():
        print(f"ERROR: reference fixture not found: {REF_PPTM}")
        raise SystemExit(1)

    raw_input = REF_PPTM.read_bytes()
    raw  = _strip_module1(raw_input)
    comp = zlib.compress(raw, 9)
    b85  = base64.b85encode(comp).decode("ascii")

    section  = _build_pptm_section(raw, comp, b85)
    existing = OUT_PY.read_text(encoding="utf-8")
    updated  = _splice(existing, section)
    OUT_PY.write_text(updated, encoding="utf-8", newline="\n")
    print(
        f"wrote {OUT_PY.relative_to(ROOT)}  "
        f"({len(raw)} -> {len(comp)} zlib -> {len(b85)} base85)"
    )


if __name__ == "__main__":
    main()
